{
  "hash": "880f77eac3327a93941141d6ae982d4a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Model selection for logistic regression\"\nsubtitle: \"Lecture 18\"\ndate: \"2025-3-27\"\nformat: revealjs\nauto-stretch: false\n---\n\n## While you wait...\n\n\n::: {.cell}\n\n:::\n\n\n::: appex\n-   Go to your `ae` project in RStudio.\n\n-   Make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   Click Pull to get today's application exercise file: *ae\\-14\\-forest\\-classification\\.qmd*.\n\n-   Wait till the you're prompted to work on the application exercise during class before editing the file.\n:::\n\n## Last time: regression with a binary response\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n## New model: logistic regression\n\nS-curve for the probability of success $p=P(y=1)$:\n\n$$\n\\hat{p}\n=\n\\frac{e^{b_0+b_1x}}{1+e^{b_0+b_1x}}.\n$$\n\nLinear model for the log-odds:\n\n$$\n\\log\\left(\\frac{\\hat{p}}{1-\\hat{p}}\\right)\n=\nb_0+b_1x.\n$$\n\nThese are equivalent.\n\n## R syntax is mostly unchanged\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple_logistic_fit <- logistic_reg() |>\n  fit(spam ~ exclaim_mess, data = email)\n\ntidy(simple_logistic_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term          estimate std.error statistic p.value\n  <chr>            <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)  -2.27      0.0553     -41.1     0    \n2 exclaim_mess  0.000272  0.000949     0.287   0.774\n```\n\n\n:::\n:::\n\n\nFitted equation for the log-odds:\n\n$$\n\\log\\left(\\frac{\\hat{p}}{1-\\hat{p}}\\right)\n=\n-2.27\n+\n0.000272\\times exclaim~mess\n$$\n\nInterpretations are strange and delicate.\n\n## Here's an alternative model\n\nDump all the predictors in:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_logistic_fit <- logistic_reg() |>\n  fit(spam ~ ., data = email)\n\ntidy(full_logistic_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 22 × 5\n   term         estimate std.error statistic  p.value\n   <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n 1 (Intercept)  -9.09e+1   9.80e+3  -0.00928 9.93e- 1\n 2 to_multiple1 -2.68e+0   3.27e-1  -8.21    2.25e-16\n 3 from1        -2.19e+1   9.80e+3  -0.00224 9.98e- 1\n 4 cc            1.88e-2   2.20e-2   0.855   3.93e- 1\n 5 sent_email1  -2.07e+1   3.87e+2  -0.0536  9.57e- 1\n 6 time          8.48e-8   2.85e-8   2.98    2.92e- 3\n 7 image        -1.78e+0   5.95e-1  -3.00    2.73e- 3\n 8 attach        7.35e-1   1.44e-1   5.09    3.61e- 7\n 9 dollar       -6.85e-2   2.64e-2  -2.59    9.64e- 3\n10 winneryes     2.07e+0   3.65e-1   5.67    1.41e- 8\n# ℹ 12 more rows\n```\n\n\n:::\n:::\n\n\n## Classification error\n\nThere are two kinds of mistakes:\n\n![](images/17/confusion-matrix.png)\n\nWe want to avoid both, but there's a trade-off.\n\n## Jargon: False negative and positive\n\n-   **False negative rate** is the *proportion* of actual positives that were classified as negatives.\n\n-   **False positive rate** is the *proportion* of actual negatives that were classified as positives.\n\n::: callout-tip\nWe want these to be low!\n:::\n\n## Jargon: Sensitivity\n\n**Sensitivity** is the *proportion* of actual positives that were correctly classified as positive.\n\n-   Also known as **true positive rate** and **recall**\n\n-   Sensitivity = 1 − False negative rate\n\n-   Useful when false negatives are more \"expensive\" than false positives\n\n::: callout-tip\nWe want this to be high!\n:::\n\n## Jargon: Specificity\n\n**Specificity** is the *proportion* of actual negatives that were correctly classified as negative\n\n-   Also known as **true negative rate**\n\n-   Specificity = 1 − False positive rate\n\n::: callout-tip\nWe want this to be high!\n:::\n\n## The augment function\n\nThe `augment` function takes a data frame and \"augments\" it by adding three new columns on the left that describe the model predictions for each row:\n\n-   `.pred_class`: model prediction ($\\hat{y}$) based on a 50% threshold;\n-   `.pred_0`: model estimate of $P(y=0)$;\n-   `.pred_1`: model estimate of $P(y=1) = 1 - P(y = 0)$.\n\n## The augment function\n\nThe `augment` function takes a data frame and \"augments\" it by adding three new columns on the left that describe the model predictions for each row:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_aug_full <- augment(full_logistic_fit, email)\nlog_aug_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,921 × 24\n   .pred_class .pred_0  .pred_1 spam  to_multiple from     cc sent_email\n   <fct>         <dbl>    <dbl> <fct> <fct>       <fct> <int> <fct>     \n 1 0             0.867 1.33e- 1 0     0           1         0 0         \n 2 0             0.943 5.70e- 2 0     0           1         0 0         \n 3 0             0.942 5.78e- 2 0     0           1         0 0         \n 4 0             0.920 7.96e- 2 0     0           1         0 0         \n 5 0             0.903 9.74e- 2 0     0           1         0 0         \n 6 0             0.901 9.87e- 2 0     0           1         0 0         \n 7 0             1.000 7.89e-12 0     1           1         0 1         \n 8 0             1.000 1.24e-12 0     1           1         1 1         \n 9 0             0.862 1.38e- 1 0     0           1         0 0         \n10 0             0.922 7.76e- 2 0     0           1         0 0         \n# ℹ 3,911 more rows\n# ℹ 16 more variables: time <dttm>, image <dbl>, attach <dbl>, dollar <dbl>,\n#   winner <fct>, inherit <dbl>, viagra <dbl>, password <dbl>, num_char <dbl>,\n#   line_breaks <int>, format <fct>, re_subj <fct>, exclaim_subj <dbl>,\n#   urgent_subj <fct>, exclaim_mess <dbl>, number <fct>\n```\n\n\n:::\n:::\n\n\n## Calculating the error rates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_aug_full |>\n  count(spam, .pred_class) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  spam  .pred_class     n\n  <fct> <fct>       <int>\n1 0     0            3521\n2 0     1              33\n3 1     0             299\n4 1     1              68\n```\n\n\n:::\n:::\n\n\n## Calculating the error rates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_aug_full |>\n  count(spam, .pred_class) |>\n  group_by(spam)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n# Groups:   spam [2]\n  spam  .pred_class     n\n  <fct> <fct>       <int>\n1 0     0            3521\n2 0     1              33\n3 1     0             299\n4 1     1              68\n```\n\n\n:::\n:::\n\n\n## Calculating the error rates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_aug_full |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n       p\n  <fct> <fct>       <int>   <dbl>\n1 0     0            3521 0.991  \n2 0     1              33 0.00929\n3 1     0             299 0.815  \n4 1     1              68 0.185  \n```\n\n\n:::\n:::\n\n\n## Calculating the error rates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_aug_full |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(\n    p = n / sum(n),\n    decision = case_when(\n      spam == \"0\" & .pred_class == \"0\" ~ \"True negative\",\n      spam == \"0\" & .pred_class == \"1\" ~ \"False positive\",\n      spam == \"1\" & .pred_class == \"0\" ~ \"False negative\",\n      spam == \"1\" & .pred_class == \"1\" ~ \"True positive\"\n    ))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n# Groups:   spam [2]\n  spam  .pred_class     n       p decision      \n  <fct> <fct>       <int>   <dbl> <chr>         \n1 0     0            3521 0.991   True negative \n2 0     1              33 0.00929 False positive\n3 1     0             299 0.815   False negative\n4 1     1              68 0.185   True positive \n```\n\n\n:::\n:::\n\n\n## But wait!\n\nIf we change the classification threshold, we change the classifications, and we change the error rates:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2-4\"}\nlog_aug_full |>\n  mutate(\n    .pred_class = if_else(.pred_1 <= 0.25, 0, 1)\n  ) |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n      p\n  <fct>       <dbl> <int>  <dbl>\n1 0               0  3263 0.918 \n2 0               1   291 0.0819\n3 1               0   172 0.469 \n4 1               1   195 0.531 \n```\n\n\n:::\n:::\n\n\n## Classification threshold: 0.00\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2-4\"}\nlog_aug_full |>\n  mutate(\n    .pred_class = if_else(.pred_1 <= 0.00, 0, 1)\n  ) |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n     p\n  <fct>       <dbl> <int> <dbl>\n1 0               1  3554     1\n2 1               1   367     1\n```\n\n\n:::\n:::\n\n\n## Classification threshold: 0.25\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2-4\"}\nlog_aug_full |>\n  mutate(\n    .pred_class = if_else(.pred_1 <= 0.25, 0, 1)\n  ) |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n      p\n  <fct>       <dbl> <int>  <dbl>\n1 0               0  3263 0.918 \n2 0               1   291 0.0819\n3 1               0   172 0.469 \n4 1               1   195 0.531 \n```\n\n\n:::\n:::\n\n\n## Classification threshold: 0.5\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2-4\"}\nlog_aug_full |>\n  mutate(\n    .pred_class = if_else(.pred_1 <= 0.50, 0, 1)\n  ) |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n       p\n  <fct>       <dbl> <int>   <dbl>\n1 0               0  3521 0.991  \n2 0               1    33 0.00929\n3 1               0   299 0.815  \n4 1               1    68 0.185  \n```\n\n\n:::\n:::\n\n\n## Classification threshold: 0.75\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2-4\"}\nlog_aug_full |>\n  mutate(\n    .pred_class = if_else(.pred_1 <= 0.75, 0, 1)\n  ) |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n       p\n  <fct>       <dbl> <int>   <dbl>\n1 0               0  3544 0.997  \n2 0               1    10 0.00281\n3 1               0   339 0.924  \n4 1               1    28 0.0763 \n```\n\n\n:::\n:::\n\n\n## Classification threshold: 1.00\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"2-4\"}\nlog_aug_full |>\n  mutate(\n    .pred_class = if_else(.pred_1 <= 1.00, 0, 1)\n  ) |>\n  count(spam, .pred_class) |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n     p\n  <fct>       <dbl> <int> <dbl>\n1 0               0  3554     1\n2 1               0   367     1\n```\n\n\n:::\n:::\n\n\n## Let's plot these error rates\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## ROC curve {.medium}\n\nIf we repeat this process for \"all\" possible thresholds $0\\leq p^\\star\\leq 1$, we trace out the **receiver operating characteristic curve** (ROC curve), which assesses the model's performance across a range of thresholds:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n## ROC curve {.scrollable}\n\n::: task\nWhich corner of the plot indicates the best model performance?\n:::\n\n![](images/18/roc-curve-annotated.png)\n\n. . .\n\nUpper left!\n\n## ROC for full model\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n## ROC for simple model\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\nComparing these two curves, the full model is better.\n\n## Model comparison\n\nThe farther up and to the left the ROC curve is, the better the classification accuracy. You can quantify this with the area under the curve.\n\n::: callout-note\nArea under the ROC curve will be our \"quality score\" for comparing logistic regression models.\n:::\n\n# Washington forests\n\n## Data {.smaller}\n\n-   The U.S. Forest Service maintains machine learning models to predict whether a plot of land is \"forested.\"\n\n-   This classification is important for research, legislation, land management, etc. purposes.\n\n-   Plots are typically remeasured every 10 years.\n\n-   The `forested` dataset contains the most recent measurement per plot.\n\n## Data: `forested` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforested\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7,107 × 20\n   forested  year elevation eastness northness roughness tree_no_tree dew_temp\n   <fct>    <dbl>     <dbl>    <dbl>     <dbl>     <dbl> <fct>           <dbl>\n 1 Yes       2005       881       90        43        63 Tree             0.04\n 2 Yes       2005       113      -25        96        30 Tree             6.4 \n 3 No        2005       164      -84        53        13 Tree             6.06\n 4 Yes       2005       299       93        34         6 No tree          4.43\n 5 Yes       2005       806       47       -88        35 Tree             1.06\n 6 Yes       2005       736      -27       -96        53 Tree             1.35\n 7 Yes       2005       636      -48        87         3 No tree          1.42\n 8 Yes       2005       224      -65       -75         9 Tree             6.39\n 9 Yes       2005        52      -62        78        42 Tree             6.5 \n10 Yes       2005      2240      -67       -74        99 No tree         -5.63\n# ℹ 7,097 more rows\n# ℹ 12 more variables: precip_annual <dbl>, temp_annual_mean <dbl>,\n#   temp_annual_min <dbl>, temp_annual_max <dbl>, temp_january_min <dbl>,\n#   vapor_min <dbl>, vapor_max <dbl>, canopy_cover <dbl>, lon <dbl>, lat <dbl>,\n#   land_type <fct>, county <fct>\n```\n\n\n:::\n:::\n\n\n## Data: `forested` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(forested)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 7,107\nColumns: 20\n$ forested         <fct> Yes, Yes, No, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes,…\n$ year             <dbl> 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005,…\n$ elevation        <dbl> 881, 113, 164, 299, 806, 736, 636, 224, 52, 2240, 104…\n$ eastness         <dbl> 90, -25, -84, 93, 47, -27, -48, -65, -62, -67, 96, -4…\n$ northness        <dbl> 43, 96, 53, 34, -88, -96, 87, -75, 78, -74, -26, 86, …\n$ roughness        <dbl> 63, 30, 13, 6, 35, 53, 3, 9, 42, 99, 51, 190, 95, 212…\n$ tree_no_tree     <fct> Tree, Tree, Tree, No tree, Tree, Tree, No tree, Tree,…\n$ dew_temp         <dbl> 0.04, 6.40, 6.06, 4.43, 1.06, 1.35, 1.42, 6.39, 6.50,…\n$ precip_annual    <dbl> 466, 1710, 1297, 2545, 609, 539, 702, 1195, 1312, 103…\n$ temp_annual_mean <dbl> 6.42, 10.64, 10.07, 9.86, 7.72, 7.89, 7.61, 10.45, 10…\n$ temp_annual_min  <dbl> -8.32, 1.40, 0.19, -1.20, -5.98, -6.00, -5.76, 1.11, …\n$ temp_annual_max  <dbl> 12.91, 15.84, 14.42, 15.78, 13.84, 14.66, 14.23, 15.3…\n$ temp_january_min <dbl> -0.08, 5.44, 5.72, 3.95, 1.60, 1.12, 0.99, 5.54, 6.20…\n$ vapor_min        <dbl> 78, 34, 49, 67, 114, 67, 67, 31, 60, 79, 172, 162, 70…\n$ vapor_max        <dbl> 1194, 938, 754, 1164, 1254, 1331, 1275, 944, 892, 549…\n$ canopy_cover     <dbl> 50, 79, 47, 42, 59, 36, 14, 27, 82, 12, 74, 66, 83, 6…\n$ lon              <dbl> -118.6865, -123.0825, -122.3468, -121.9144, -117.8841…\n$ lat              <dbl> 48.69537, 47.07991, 48.77132, 45.80776, 48.07396, 48.…\n$ land_type        <fct> Tree, Tree, Tree, Tree, Tree, Tree, Non-tree vegetati…\n$ county           <fct> Ferry, Thurston, Whatcom, Skamania, Stevens, Stevens,…\n```\n\n\n:::\n:::\n\n\n## Outcome and predictors {.smaller}\n\n-   Outcome: `forested` - Factor, `Yes` or `No`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(forested$forested)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Yes\" \"No\" \n```\n\n\n:::\n:::\n\n\n-   Predictors: 18 remotely-sensed and easily-accessible predictors:\n\n    -   numeric variables based on weather and topography\n\n    -   categorical variables based on classifications from other governmental organizations\n\n## `?forested`\n\n<iframe width=\"900\" height=\"500\" src=\"https://simonpcouch.github.io/forested/reference/forested.html\" title=\"forested\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen>\n\n</iframe>\n\n## Should we include a predictor?\n\nTo determine whether we should include a predictor in a model, we should start by asking:\n\n::: incremental\n-   Is it ethical to use this variable? (Or even legal?)\n\n-   Will this variable be available at prediction time?\n\n-   Does this variable contribute to explainability?\n:::\n\n# Data splitting and spending\n\n## We've been cheating!\n\n::: incremental\n-   So far, we've been using all the data we have for building models. In predictive contexts, this would be considered *cheating*.\n\n-   Evaluating model performance for predicting outcomes that were used when building the models is like evaluating your learning with questions whose answers you've already seen.\n:::\n\n## Spending your data {.smaller}\n\nFor predictive models (used primarily in machine learning), we typically split data into training and test sets:\n\n![](images/18/test-train-split-1.svg){fig-align=\"center\"}\n\n-   The **training set** is used to estimate model parameters.\n\n-   The **test set** is used to find an independent assessment of model performance.\n\n. . .\n\n::: callout-warning\nDo not use, or even peek at, the test set during training.\n:::\n\n## How much to spend?\n\n::: incremental\n-   The more data we spend (use in training), the better estimates we’ll get.\n\n-   Spending too much data in training prevents us from computing a good assessment of predictive performance.\n\n-   Spending too much data in testing prevents us from computing a good estimate of model parameters.\n:::\n\n## The initial split\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20241112)\nforested_split <- initial_split(forested)\nforested_split\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<Training/Testing/Total>\n<5330/1777/7107>\n```\n\n\n:::\n:::\n\n\n## Setting a seed {.smaller}\n\n::: task\nWhat does `set.seed()` do?\n:::\n\n::: incremental\n-   To create that split of the data, R generates “pseudo-random” numbers: while they are made to behave like random numbers, their generation is deterministic given a “seed”.\n\n-   This allows us to reproduce results by setting that seed.\n\n-   Which seed you pick doesn’t matter, as long as you don’t try a bunch of seeds and pick the one that gives you the best performance.\n:::\n\n## Accessing the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforested_train <- training(forested_split)\nforested_test <- testing(forested_split)\n```\n:::\n\n\n## The training set {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforested_train\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,330 × 20\n   forested  year elevation eastness northness roughness tree_no_tree dew_temp\n   <fct>    <dbl>     <dbl>    <dbl>     <dbl>     <dbl> <fct>           <dbl>\n 1 Yes       2013       315      -17        98        92 Tree             5.83\n 2 No        2018       374       93       -34        23 No tree          0.7 \n 3 No        2017       377       44       -89         1 Tree             1.83\n 4 Yes       2013       541       31       -94       139 Tree             4.19\n 5 Yes       2017       680       14       -98        20 Tree             0.79\n 6 Yes       2017      1482       76       -64        43 Tree            -0.18\n 7 No        2020        84       42       -90        12 No tree          6.9 \n 8 Yes       2011       210       34        93        16 Tree             5.52\n 9 No        2020       766       14        98        20 No tree          1.52\n10 Yes       2013      1559       98        16        79 Tree            -3.45\n# ℹ 5,320 more rows\n# ℹ 12 more variables: precip_annual <dbl>, temp_annual_mean <dbl>,\n#   temp_annual_min <dbl>, temp_annual_max <dbl>, temp_january_min <dbl>,\n#   vapor_min <dbl>, vapor_max <dbl>, canopy_cover <dbl>, lon <dbl>, lat <dbl>,\n#   land_type <fct>, county <fct>\n```\n\n\n:::\n:::\n\n\n## The testing data {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforested_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,777 × 20\n   forested  year elevation eastness northness roughness tree_no_tree dew_temp\n   <fct>    <dbl>     <dbl>    <dbl>     <dbl>     <dbl> <fct>           <dbl>\n 1 Yes       2005       881       90        43        63 Tree             0.04\n 2 Yes       2005       636      -48        87         3 No tree          1.42\n 3 Yes       2005      2240      -67       -74        99 No tree         -5.63\n 4 Yes       2014       940      -93        35        50 Tree            -0.15\n 5 No        2014       246       22       -97         5 Tree             2.41\n 6 No        2014       419       86       -49         5 No tree          1.87\n 7 No        2014       308      -70       -70         4 No tree          3.07\n 8 No        2014       302      -31       -94         1 No tree          2.55\n 9 No        2014       340      -54        83        60 No tree          1.29\n10 No        2014       792      -61       -79        30 No tree          0.25\n# ℹ 1,767 more rows\n# ℹ 12 more variables: precip_annual <dbl>, temp_annual_mean <dbl>,\n#   temp_annual_min <dbl>, temp_annual_max <dbl>, temp_january_min <dbl>,\n#   vapor_min <dbl>, vapor_max <dbl>, canopy_cover <dbl>, lon <dbl>, lat <dbl>,\n#   land_type <fct>, county <fct>\n```\n\n\n:::\n:::\n\n\n# Exploratory data analysis\n\n## Initial questions {.smaller}\n\n-   What’s the distribution of the outcome, `forested`?\n\n-   What’s the distribution of numeric variables like `precip_annual`?\n\n-   How does the distribution of forested differ across the categorical and numerical variables?\n\n. . .\n\n::: task\nWhich dataset should we use for the exploration? The entire data `forested`, the training data `forested_train`, or the testing data `forested_test`?\n:::\n\n## `forested`\n\nWhat’s the distribution of the outcome, `forested`?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(forested_train, aes(x = forested)) +\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n## `forested`\n\nWhat’s the distribution of the outcome, `forested`?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforested_train |>\n  count(forested) |>\n  mutate(\n    p = n / sum(n)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  forested     n     p\n  <fct>    <int> <dbl>\n1 Yes       2917 0.547\n2 No        2413 0.453\n```\n\n\n:::\n:::\n\n\n## `precip_annual`\n\nWhat’s the distribution of `precip_annual`?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(forested_train, aes(x = precip_annual)) +\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-26-1.png){width=960}\n:::\n:::\n\n\n## `forested` and `precip_annual` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  forested_train,\n  aes(x = precip_annual, fill = forested, group = forested)\n  ) +\n  geom_histogram(binwidth = 200, position = \"identity\", alpha = 0.7) +\n  scale_fill_manual(values = c(\"Yes\" = \"forestgreen\", \"No\" = \"gold2\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-27-1.png){width=960}\n:::\n:::\n\n\n## `forested` and `precip_annual` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"|5\"}\nggplot(\n  forested_train,\n  aes(x = precip_annual, fill = forested, group = forested)\n  ) +\n  geom_histogram(binwidth = 200, position = \"fill\", alpha = 0.7) +\n  scale_fill_manual(values = c(\"Yes\" = \"forestgreen\", \"No\" = \"gold2\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n\n## `forested` and `tree_no_tree` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(forested_train, aes(x = tree_no_tree, fill = forested)) +\n  geom_bar(position = \"fill\") +\n  scale_fill_manual(values = c(\"Yes\" = \"forestgreen\", \"No\" = \"gold2\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n\n## `forested` and `lat` / `lon` {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(forested_train, aes(x = lon, y = lat, color = forested)) +\n  geom_point(alpha = 0.7) +\n  scale_color_manual(values = c(\"Yes\" = \"forestgreen\", \"No\" = \"gold2\")) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](18-model-selection_files/figure-revealjs/unnamed-chunk-30-1.png){width=960}\n:::\n:::\n\n\n# Next steps\n\n## Next steps {.smaller}\n\n::: incremental\n-   Fit models on training data\n\n-   Make predictions on testing data\n\n-   Evaluate predictions on testing data:\n\n    -   Linear models: R-squared, adjusted R-squared, RMSE (root mean squared error), etc.\n    -   Logistic models: False negative and positive rates, AUC (area under the curve), etc.\n\n-   Make decisions based on model predictive performance, validity across various testing/training splits (aka \"cross validation\"), explainability\n:::\n\n. . .\n\n::: callout-note\nWe will only learn about a subset of these in this course, but you can go further into these ideas in STA 210 or STA 221 as well as in various machine learning courses.\n:::\n\n## ae\\-14\\-forest\\-classification {.smaller}\n\n::: appex\n-   Go to your ae project in RStudio.\n\n-   If you haven't yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   If you haven't yet done so, click Pull to get today's application exercise file: *ae\\-14\\-forest\\-classification\\.qmd*. You might be prompted to install **forested**, say yes.\n\n-   Work through the application exercise in class, and render, commit, and push your edits.\n:::\n",
    "supporting": [
      "18-model-selection_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}