{
  "hash": "9fac73b0ef46e9ad8c7770ac2eab3954",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference conclusion\"\nsubtitle: \"Lecture 22\"\ndate: \"2025-4-14\"\nformat: revealjs\nauto-stretch: false\n---\n\n# Course admin\n\n## While you wait\n\n\n::: {.cell}\n\n:::\n\n\n-   Go to your `ae` project in RStudio.\n\n-   Make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   Click Pull to get today's application exercise file: *ae\\-18\\-card\\-krueger\\.qmd*.\n\n-   Wait until you're prompted to work on the application exercise during class before editing the file.\n\n## The home stretch\n\n::: incremental\n1.  **Tuesday 4/15**: finish statistical inference\n\n2.  **Thursday 4/17**: communicating data science results\n\n3.  **Monday 4/21**: lab is a project work period\n\n4.  **Tuesday 4/22**: Farewell!\n\n5.  **Wednesday 4/23**: submit final project\n\n6.  **Monday 4/28**: submit peer eval 4\n\n7.  **Tuesday 4/29**: final exam\n:::\n\n## It's not too late to make something happen\n\n60% of the grade has yet to be counted. Furthermore...\n\n::: incremental\n-   We drop the lowest lab;\n\n-   We drop *6* AEs (6 / 19 = 0.315);\n\n-   We replace one in-class midterm with the final exam score (if it's better).\n\n-   If you missed Milestone 1, we replace with peer eval score;\n\n-   We drop one of the first three peer evals.\n:::\n\n# Recap: statistical inference\n\n## Point estimation: what's your best guess? {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mtcars, aes(x = wt, y = mpg)) + \n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n## Point estimation: what's your best guess? {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(mpg ~ wt, data = mtcars) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    37.3      1.88      19.9  8.24e-19\n2 wt             -5.34     0.559     -9.56 1.29e-10\n```\n\n\n:::\n:::\n\n\n\n## Sampling variability \n\nDifferent data >> Different estimate. But how different?\n\n- **Reassuring**: recompute your estimate on other data and get basically the same answer. Sampling variation is low. Uncertainty is low. Results are more reliable;\n\n- **Concerning**: recompute your estimate on new data and get a wildly different answer. Sampling variation is high. Uncertainty is high. Results are less reliable.\n\nHow do we operationalize this?\n\n## The bootstrap\n\nConstruct different, alternative datasets by sampling *with replacement* from your original data. Each bootstrap sample gives you a different estimate, and you can see how vigorously they wiggle around:\n\n\n::: {.cell}\n\n:::\n\n\n::: columns\n::: {.column width=\"49%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"49%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Interval estimation \n\nUse the bootstrap distribution to construct a range of likely values for the unknown parameter:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\nWe use quantiles (think IQR), but there are other ways.\n\n## Hypothesis testing {.scrollable}\n\n::: incremental\n-   Two competing claims about $\\beta_1$: $$\n    \\begin{aligned}\n    H_0&: \\beta_1=0\\quad(\\text{nothing going on})\\\\\n    H_A&: \\beta_1\\neq0\\quad(\\text{something going on})\n    \\end{aligned}\n    $$\n\n-   Do the data strongly favor one or the other?\n\n-   How can we quantify this?\n:::\n\n## Hypothesis testing {.scrollable}\n\n::: incremental\n-   Think hypothetically: if the null hypothesis were in fact true, would my results be out of the ordinary?\n\n    -   if no, then the null could be true;\n    -   if yes, then the null might be bogus;\n\n-   My results represent the reality of actual data. If they conflict with the null, then you throw out the null and stick with reality;\n\n-   How do we *quantify* \"would my results be out of the ordinary\"?\n:::\n\n## Null distribution {.medium .scrollable}\n\nIf the null happened to be true, how would we expect our results to vary across datasets? We can use simulation to answer this:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\nThis is how the world should look *if the null is true*.\n\n## Null distribution versus reality {.medium .scrollable}\n\nLocate the *actual* results of your *actual* data analysis under the null distribution. Are they in the middle? Are they in the tails?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\nAre these results in harmony or conflict with the null?\n\n## Null distribution versus reality {.medium .scrollable}\n\nLocate the *actual* results of your *actual* data analysis under the null distribution. Are they in the middle? Are they in the tails?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\nAre these results in harmony or conflict with the null?\n\n## Null distribution versus reality {.medium .scrollable}\n\nLocate the *actual* results of your *actual* data analysis under the null distribution. Are they in the middle? Are they in the tails?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\nAre these results in harmony or conflict with the null?\n\n## *p*-value {.scrollable}\n\n::: incremental\nThe $p$-value is the probability of being *even farther out* in the tails of the null distribution than your results already were.\n\n-   if this number is very low, then your results would be out of the ordinary if the null were true, so maybe the null was never true to begin with;\n\n-   if this number is high, then your results may be perfectly compatible with the null.\n:::\n\n## *p*-value {.scrollable}\n\n*p*-value is the fraction of the histogram area shaded red:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n. . .\n\nBig ol' *p*-value. Null looks plausible\n\n## *p*-value {.scrollable}\n\n*p*-value is the fraction of the histogram area shaded red:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n. . .\n\n*p*-value is basically zero. Null looks bogus.\n\n## *p*-value {.scrollable}\n\n*p*-value is the fraction of the histogram area shaded red:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n. . .\n\n*p*-value is...kinda small? Null looks...?\n\n## Discernibility level {.scrollable}\n\n::: incremental\n-   How do we decide if the *p*-value is big enough or small enough?\n\n-   Pick a threshold $\\alpha\\in[0,\\,1]$ called the *discernibility level*:\n\n    -   If $p\\text{-value} < \\alpha$, reject null and accept alternative;\n    -   If $p\\text{-value} \\geq \\alpha$, fail to reject null;\n\n-   Standard choices: $\\alpha=0.01, 0.05, 0.1, 0.15$.\n:::\n\n\n\n\n# Redux: association does not imply causation...until it does?\n\n## Plenty of nonsense correlations out there\n\n![](images/22/silly1.png){fig-align=\"center\"}\n\n## Plenty of nonsense correlations out there\n\n![](images/22/silly2.png){fig-align=\"center\"}\n\n## Plenty of nonsense correlations out there\n\n![](images/22/silly3.png){fig-align=\"center\"}\n\n## So, when can we draw causal conclusions?\n\n::: incremental\n- Best hope: run a controlled, randomized experiment:\n\n    - get a big, representative, random sample from target population;\n    - randomly divide subjects into treatment and control;\n    - difference in outcomes was *caused* by the treatment alone;\n    - but this may be too costly or unethical.\n    \n- Observational data are very challenging:\n\n    - you couldn't control gosh darned thing;\n    - different outcomes could be caused by confounding factors, which you may or may not have measured.\n:::\n\n## A proper, controlled experiment \n\nDoes treatment using embryonic stem cells (ESCs) help improve heart function following a heart attack? Each sheep in the study was randomly assigned to the ESC or control group, and the change in their hearts' pumping capacity was measured in the study. A positive value corresponds to increased pumping capacity, which generally suggests a stronger recovery.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(stem_cell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{style='font-size: 0.5em'}\nRows: 18\nColumns: 3\n$ trmt   <fct> ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, ctrl, esc, esc,…\n$ before <dbl> 35.25, 36.50, 39.75, 39.75, 41.75, 45.00, 47.00, 52.00, 52.00, …\n$ after  <dbl> 29.50, 29.50, 36.25, 38.00, 37.50, 42.75, 39.00, 45.25, 52.25, …\n```\n\n\n:::\n:::\n\n\n## ABV {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem_cell <- stem_cell |>\n  mutate(change = after - before)\n\nggplot(stem_cell, aes(x = change, y = trmt)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## Model fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(change ~ trmt, data = stem_cell) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)    -4.33      1.38     -3.14 0.00639\n2 trmtesc         7.83      1.95      4.01 0.00102\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{change}=-4.33+7.83\\times \\texttt{esc}\n$$\n\n\n## Remember... {.scrollable}\n\n$$\n\\widehat{change}=-4.33+7.83\\times \\texttt{esc}\n$$\n\n::: incremental\n- `trmt` is categorical with two levels: `ctrl` (0) and `esc` (1). \n- The control group has `esc = 0`, so \n$$\n\\widehat{change} = -4.33;\n$$\n\n- The treatment group has `esc = 1`, so \n$$\n\\widehat{change} = -4.33+7.83=3.5.\n$$\n:::\n\n## Those were not magic numbers \n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem_cell |>\n  group_by(trmt) |>\n  summarize(\n    mean_change = mean(change)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  trmt  mean_change\n  <fct>       <dbl>\n1 ctrl        -4.33\n2 esc          3.5 \n```\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-note\n## Don't forget!\n\nIn a simple linear regression with a numerical response and a binary predictor, the slope estimate is the difference in the average response between the two groups.\n\n:::\n\n## Confidence interval\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\nWe are 95% confident that the true mean difference is between 4.34 and 11.7.\n\n## Competing claims\n\nAre the data sufficiently informative to tell the difference between these two possibilities?\n\n$$\n\\begin{aligned}\nH_0&: \\beta_1=0 && (\\text{no effect})\\\\\nH_0&: \\beta_1\\neq0 && (\\text{some effect})\\\\\n\\end{aligned}\n$$\n\n- $\\beta_1$ is the difference in mean response between the treatment and control group;\n- the alternative does not specify if the effect is positive or negative;\n- the alternative does not specify that the effect is \"large\".\n\n## Hypothesis test\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n. . . \n\nThe p-value is basically zero.\n\n## Cardinal Sins in Statistics No. 426\n\n::: incremental \n- In a hypothetical world where the treatment has no effect, it would be very unlikely to get results like the ones we did;\n\n- Evidence is sufficient to *reject the null*. There is *some* effect;\n\n- If you are convinced by the experimental design, the effect is *causal*;\n\n- Is the effect large and meaningful and something you should base major decisions on? Statistics cannot answer that question!\n:::\n\n. . .\n\n> Statistical discernibility $\\neq$ Substantive importance\n\n## A purely observational study \n\nA random sample of US births from 2014:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(births14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{style='font-size: 0.6em'}\nRows: 1,000\nColumns: 13\n$ fage           <int> 34, 36, 37, NA, 32, 32, 37, 29, 30, 29, 30, 34, 28, 28,…\n$ mage           <dbl> 34, 31, 36, 16, 31, 26, 36, 24, 32, 26, 34, 27, 22, 31,…\n$ mature         <chr> \"younger mom\", \"younger mom\", \"mature mom\", \"younger mo…\n$ weeks          <dbl> 37, 41, 37, 38, 36, 39, 36, 40, 39, 39, 42, 40, 40, 39,…\n$ premie         <chr> \"full term\", \"full term\", \"full term\", \"full term\", \"pr…\n$ visits         <dbl> 14, 12, 10, NA, 12, 14, 10, 13, 15, 11, 14, 16, 20, 15,…\n$ gained         <dbl> 28, 41, 28, 29, 48, 45, 20, 65, 25, 22, 40, 30, 31, NA,…\n$ weight         <dbl> 6.96, 8.86, 7.51, 6.19, 6.75, 6.69, 6.13, 6.74, 8.94, 9…\n$ lowbirthweight <chr> \"not low\", \"not low\", \"not low\", \"not low\", \"not low\", …\n$ sex            <chr> \"male\", \"female\", \"female\", \"male\", \"female\", \"female\",…\n$ habit          <chr> \"nonsmoker\", \"nonsmoker\", \"nonsmoker\", \"nonsmoker\", \"no…\n$ marital        <chr> \"married\", \"married\", \"married\", \"not married\", \"marrie…\n$ whitemom       <chr> \"white\", \"white\", \"not white\", \"white\", \"white\", \"white…\n```\n\n\n:::\n:::\n\n\nDoes a mother's smoking `habit` *cause* low birth `weight`? Perhaps, but concluding that from these data might be challenging.\n\n## Visualize {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirths14 |>\n  drop_na(weight, habit) |>\n  ggplot(aes(x = weight, y = habit)) + \n  geom_boxplot(alpha = 0.5) + \n  labs(\n    x = \"Birth Weight (lbs)\",\n    y = \"Mother smoking status\"\n  )\n```\n\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\n## Estimate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  fit(weight ~ habit, data = births14) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic    p.value\n  <chr>          <dbl>     <dbl>     <dbl>      <dbl>\n1 (Intercept)    7.27     0.0435    167.   0         \n2 habitsmoker   -0.593    0.128      -4.65 0.00000382\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{weight}=7.27-0.59\\times \\texttt{smoker}.\n$$\n\n## Confidence interval \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n## Hypothesis test\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](22-inference-wrapup_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n\n. . . \n\nThe p-value is basically zero.\n\n\n## Cardinal Sins in Statistics No. 2135\n\n::: incremental\n- Evidence is sufficient to reject the null: smoking during pregnancy is *associated* with a difference in birth weight;\n\n- Is smoking *causing* birth weight to change?\n\n- The data are observational, and there are many unmeasured factors that could bear on both `habit` and `weight`.\n\n- Maybe there is a causal relationship, and maybe it can be teased out with data like these, but we have all of our work ahead of us.\n:::\n\n. . .\n\n> Just because there is a statistically discernible association does not mean there is a causal relationship.\n\n## Natural experiments\n\nThe four-leaf clover of applied statistics:\n\n- You stumble upon observational data where \"nature\" has accidentally randomized treatment/control for you, *as if* a controlled experiment was performed;\n\n- If you're extra lucky and careful and shrewd, *maybe* you can use these special data to tell a causal story.\n\n\n## Natural experiments\n\n{{< video https://www.youtube.com/embed/OkJH6sapQMA width=\"900\" height=\"600\" >}}\n\n## Nobel prize winning research\n\n![](images/22/angrist.png){fig-align=\"center\"}\n\n## Another natural experiment: Card and Krueger {.scrollable}\n\n![](images/labs/card-krueger.jpg){fig-align=\"center\"}\n\n## The ECON 101 story\n\n![](images/22/econ101.png){fig-align=\"center\"}\nThis is a claim (hypothesis!) about how the data will look. Let's see!\n\n## ae\\-18\\-card\\-krueger {.smaller}\n\n::: appex\n-   Go to your ae project in RStudio.\n\n-   If you haven't yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   If you haven't yet done so, click Pull to get today's application exercise file: *ae\\-18\\-card\\-krueger\\.qmd*.\n\n-   Work through the application exercise in class, and render, commit, and push your edits.\n:::\n",
    "supporting": [
      "22-inference-wrapup_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}