{
  "hash": "7724a22f3b3946038f183e404665f369",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Midterm 2 Practice Questions\nexecute:\n  echo: false\n---\n\n::: {.callout-tip collapse=\"true\"}\n## Solutions\n\nSee [here](https://sta199-s25.github.io/exam/midterm-2-practice-solns.html).\n:::\n\n\n::: {.cell}\n\n:::\n\n\n# Part 1 - Blizzard\n\n\n::: {.cell}\n\n:::\n\n\nIn 2020, employees of Blizzard Entertainment circulated a spreadsheet to anonymously share salaries and recent pay increases amidst rising tension in the video game industry over wage disparities and executive compensation. (Source: [Blizzard Workers Share Salaries in Revolt Over Pay](https://www.bloomberg.com/news/articles/2020-08-03/blizzard-workers-share-salaries-in-revolt-over-wage-disparities))\n\nThe name of the data frame used for this analysis is `blizzard_salary` and the variables are:\n\n-   `percent_incr`: Raise given in July 2020, as percent increase with values ranging from 1 (1% increase to 21.5 (21.5% increase)\n\n-   `salary_type`: Type of salary, with levels `Hourly` and `Salaried`\n\n-   `annual_salary`: Annual salary, in USD, with values ranging from \\$50,939 to \\$216,856.\n\n-   `performance_rating`: Most recent review performance rating, with levels `Poor`, `Successful`, `High`, and `Top`. The `Poor` level is the lowest rating and the `Top` level is the highest rating.\n\nThe top ten rows of `blizzard_salary` are shown below:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 409 × 4\n   percent_incr salary_type annual_salary performance_rating\n          <dbl> <chr>               <dbl> <chr>             \n 1          1   Salaried               1  High              \n 2          1   Salaried               1  Successful        \n 3          1   Salaried               1  High              \n 4          1   Hourly             33987. Successful        \n 5         NA   Hourly             34798. High              \n 6         NA   Hourly             35360  <NA>              \n 7         NA   Hourly             37440  <NA>              \n 8          0   Hourly             37814. <NA>              \n 9          4   Hourly             41101. Top               \n10          1.2 Hourly             42328  <NA>              \n# ℹ 399 more rows\n```\n\n\n:::\n:::\n\n\n## Question 1\n\nYou fit a model for predicting raises (`percent_incr`) from salaries (`annual_salary`). We'll call this model `raise_1_fit`. A tidy output of the model is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term           estimate  std.error statistic   p.value\n  <chr>             <dbl>      <dbl>     <dbl>     <dbl>\n1 (Intercept)   1.87      0.432           4.33 0.0000194\n2 annual_salary 0.0000155 0.00000452      3.43 0.000669 \n```\n\n\n:::\n:::\n\n\nWhich of the following is the best interpretation of the slope coefficient?\n\na.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 1.55%.\nb.  For every additional \\$1,000 of annual salary, the raise goes up by 0.0155%.\nc.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 0.0155%.\nd.  For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 1.87%.\n\n## Question 2\n\nYou then fit a model for predicting raises (`percent_incr`) from salaries (`annual_salary`) and performance ratings (`performance_rating`). We'll call this model `raise_2_fit`. Which of the following is definitely true based on the information you have so far?\n\na.  Intercept of `raise_2_fit` is higher than intercept of `raise_1_fit`.\nb.  Slope of `raise_2_fit` is higher than RMSE of `raise_1_fit`.\nc.  Adjusted $R^2$ of `raise_2_fit` is higher than adjusted $R^2$ of `raise_1_fit`.\nd.  $R^2$ of `raise_2_fit` is higher $R^2$ of `raise_1_fit`.\n\n## Question 3\n\nThe tidy model output for the `raise_2_fit` model you fit is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term                            estimate  std.error statistic  p.value\n  <chr>                              <dbl>      <dbl>     <dbl>    <dbl>\n1 (Intercept)                   3.55       0.508           6.99 1.99e-11\n2 annual_salary                 0.00000989 0.00000436      2.27 2.42e- 2\n3 performance_ratingPoor       -4.06       1.42           -2.86 4.58e- 3\n4 performance_ratingSuccessful -2.40       0.397          -6.05 4.68e- 9\n5 performance_ratingTop         2.99       0.715           4.18 3.92e- 5\n```\n\n\n:::\n:::\n\n\nWhen your teammate sees this model output, they remark \"The coefficient for `performance_ratingSuccessful` is negative, that's weird. I guess it means that people who get successful performance ratings get lower raises.\" How would you respond to your teammate?\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n## Question 4\n\nUltimately, your teammate decides they don't like the negative slope coefficients in the model output you created (not that there's anything wrong with negative slope coefficients!), does something else, and comes up with the following model output.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term                            estimate  std.error statistic    p.value\n  <chr>                              <dbl>      <dbl>     <dbl>      <dbl>\n1 (Intercept)                  -0.511      1.47          -0.347 0.729     \n2 annual_salary                 0.00000989 0.00000436     2.27  0.0242    \n3 performance_ratingSuccessful  1.66       1.42           1.17  0.242     \n4 performance_ratingHigh        4.06       1.42           2.86  0.00458   \n5 performance_ratingTop         7.05       1.53           4.60  0.00000644\n```\n\n\n:::\n:::\n\n\nUnfortunately they didn't write their code in a Quarto document, instead just wrote some code in the Console and then lost track of their work. They remember using the `fct_relevel()` function and doing something like the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblizzard_salary <- blizzard_salary |>\n  mutate(performance_rating = fct_relevel(performance_rating, ___))\n```\n:::\n\n\nWhat should they put in the blanks to get the same model output as above?\n\na.  \"Poor\", \"Successful\", \"High\", \"Top\"\nb.  \"Successful\", \"High\", \"Top\"\nc.  \"Top\", \"High\", \"Successful\", \"Poor\"\nd.  Poor, Successful, High, Top\n\n## Question 5\n\nSuppose we fit a model to predict `percent_incr` from `annual_salary` and `salary_type`. A tidy output of the model is shown below.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term                 estimate  std.error statistic p.value\n  <chr>                   <dbl>      <dbl>     <dbl>   <dbl>\n1 (Intercept)         1.24      0.570           2.18 0.0300 \n2 annual_salary       0.0000137 0.00000464      2.96 0.00329\n3 salary_typeSalaried 0.913     0.544           1.68 0.0938 \n```\n\n\n:::\n:::\n\n\nWhich of the following visualizations represent this model? Explain your reasoning.\n\n\n::: {#fig-raise-salary-type .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Option 1](midterm-2-practice_files/figure-html/fig-raise-salary-type-1.png){#fig-raise-salary-type-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Option 2](midterm-2-practice_files/figure-html/fig-raise-salary-type-2.png){#fig-raise-salary-type-2 width=672}\n:::\n\n::: {.cell-output-display}\n![Option 3](midterm-2-practice_files/figure-html/fig-raise-salary-type-3.png){#fig-raise-salary-type-3 width=672}\n:::\n\n::: {.cell-output-display}\n![Option 4](midterm-2-practice_files/figure-html/fig-raise-salary-type-4.png){#fig-raise-salary-type-4 width=672}\n:::\n\nVisualizations of the relationship between percent increase, annual \nsalary, and salary type\n\n:::\n\n\n::: {.content-visible when-format=\"pdf\"}\n{{< pagebreak >}}\n:::\n\n{{< pagebreak >}}\n\n## Question 6\n\nSuppose you now fit a model to predict the natural log of percent increase, `log(percent_incr)`, from performance rating. The model is called `raise_4_fit`.\n\n\n::: {.cell}\n\n:::\n\n\nYou're provided the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(raise_4_fit) |>\n  select(term, estimate) |>\n  mutate(exp_estimate = exp(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term                         estimate exp_estimate\n  <chr>                           <dbl>        <dbl>\n1 (Intercept)                     -7.15     0.000786\n2 performance_ratingSuccessful     6.93  1025.      \n3 performance_ratingHigh           8.17  3534.      \n4 performance_ratingTop            8.91  7438.      \n```\n\n\n:::\n:::\n\n\nBased on this, which of the following is true?\n\na\\. The model predicts that the percentage increase employees with Successful performance get, on average, is higher by 10.25% compared to the employees with Poor performance rating.\n\nb\\. The model predicts that the percentage increase employees with Successful performance get, on average, is higher by 6.93% compared to the employees with Poor performance rating.\n\nc\\. The model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 1025 compared to the employees with Poor performance rating.\n\nd\\. The model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 6.93 compared to the employees with Poor performance rating.\n\n# Part 2 - Movies\n\nThe data for this part comes from the Internet Movie Database (IMDB). Specifically, the data are a random sample of movies released between 1980 and 2020.\n\n\n::: {.cell}\n\n:::\n\n\nThe name of the data frame used for this analysis is `movies`, and it contains the variables shown in @tbl-data-dictionary.\n\n\\setcounter{table}{0}\n\n| Variable          | Description                                                             |\n|----------------------|--------------------------------------------------|\n| `name`            | name of the movie                                                       |\n| `rating`          | rating of the movie (R, PG, etc.)                                       |\n| `genre`           | main genre of the movie.                                                |\n| `runtime`         | duration of the movie                                                   |\n| `year`            | year of release                                                         |\n| `release_date`    | release date (YYYY-MM-DD)                                               |\n| `release_country` | release country                                                         |\n| `score`           | IMDB user rating                                                        |\n| `votes`           | number of user votes                                                    |\n| `director`        | the director                                                            |\n| `writer`          | writer of the movie                                                     |\n| `star`            | main actor/actress                                                      |\n| `country`         | country of origin                                                       |\n| `budget`          | the budget of a movie (some movies don't have this, so it appears as 0) |\n| `gross`           | revenue of the movie                                                    |\n| `company`         | the production company                                                  |\n\n: Data dictionary for `movies` {#tbl-data-dictionary tbl-colwidths=\"\\[20,80\\]\"}\n\nThe first thirty rows of the `movies` data frame are shown in @tbl-data, with variable types suppressed (since we'll ask about them later).\n\n{{< pagebreak >}}\n\n\n::: {.cell}\n\n:::\n\n\n````{=tex}\n\\begin{landscape}\n\n::: {#tbl-data}\nFirst 30 rows of `movies`, with variable types suppressed.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 500 × 16\n   name           score runtime genre     rating    release_country release_date\n 1 Blue City        4.4 83 mins Action    R         United States   1986-05-02  \n 2 Winter Sleep     8.1 196     Drama     Not Rated Turkey          2014-06-12  \n 3 Rang De Basan…   8.1 167     Comedy    Not Rated United States   2006-01-26  \n 4 Pokémon Detec…   6.6 104     Action    PG        United States   2019-05-10  \n 5 A Bad Moms Ch…   5.6 104     Comedy    R         United States   2017-11-01  \n 6 Replicas         5.5 107     Drama     PG-13     United States   2019-01-11  \n 7 Windy City       5.8 103     Drama     R         Uruguay         1986-01-01  \n 8 War for the P…   7.4 140     Action    PG-13     United States   2017-07-14  \n 9 Tales from th…   6.4 98      Crime     R         United States   1995-05-24  \n10 Fire with Fire   6.5 103     Drama     PG-13     United States   1986-05-09  \n11 Raising Helen    6   119     Comedy    PG-13     United States   2004-05-28  \n12 Feeling Minne…   5.4 99      Comedy    R         United States   1996-09-13  \n13 The Babe         5.9 115     Biography PG        United States   1992-04-17  \n14 The Real Blon…   6   105     Comedy    R         United States   1998-02-27  \n15 To vlemma tou…   7.6 176     Drama     Not Rated United States   1997-11-01  \n16 Going the Dis…   6.3 102     Comedy    R         United States   2010-09-03  \n17 Jung on zo       6.8 103     Action    R         Hong Kong       1993-06-24  \n18 Rita, Sue and…   6.5 93      Comedy    R         United Kingdom  1987-05-29  \n19 Phone Booth      7   81      Crime     R         United States   2003-04-04  \n20 Happy Death D…   6.6 96      Comedy    PG-13     United States   2017-10-13  \n21 Barely Legal     4.7 90      Comedy    R         Thailand        2006-05-25  \n22 Three Kings      7.1 114     Action    R         United States   1999-10-01  \n23 Menace II Soc…   7.5 97      Crime     R         United States   1993-05-26  \n24 Four Rooms       6.8 98      Comedy    R         United States   1995-12-25  \n25 Quartet          6.8 98      Comedy    PG-13     United States   2013-03-01  \n26 Tape             7.2 86      Drama     R         Denmark         2002-07-12  \n27 Marked for De…   6   93      Action    R         United States   1990-10-05  \n28 Congo            5.2 109     Action    PG-13     United States   1995-06-09  \n29 Stop-Loss        6.4 112     Drama     R         United States   2008-03-28  \n30 Con Air          6.9 115     Action    R         United States   1997-06-06  \n      budget     gross  votes  year director         writer        star         \n                                      \n 1  10000000   6947787   1100  1986 Michelle Manning Ross Macdona… Judd Nelson  \n 2        NA   4018705  48000  2014 Nuri Bilge Ceyl… Ebru Ceylan   Haluk Bilgin…\n 3        NA  10800778 115000  2006 Rakeysh Ompraka… Renzil D'Sil… Aamir Khan   \n 4 150000000 433921300 146000  2019 Rob Letterman    Dan Hernandez Ryan Reynolds\n 5  28000000 130560428  46000  2017 Jon Lucas        Jon Lucas     Mila Kunis   \n 6  30000000   9330075  34000  2018 Jeffrey Nachman… Chad St. John Keanu Reeves \n 7        NA    343890    262  1984 Armyan Bernstein Armyan Berns… John Shea    \n 8 150000000 490719763 235000  2017 Matt Reeves      Mark Bomback  Andy Serkis  \n 9   6000000  11837928   7400  1995 Rusty Cundieff   Rusty Cundie… Clarence Wil…\n10        NA   4636169   1500  1986 Duncan Gibbins   Bill Phillips Craig Sheffer\n11  50000000  49718611  36000  2004 Garry Marshall   Patrick J. C… Kate Hudson  \n12        NA   3124440  11000  1996 Steven Baigelman Steven Baige… Keanu Reeves \n13        NA  19930973   9300  1992 Arthur Hiller    John Fusco    John Goodman \n14        NA     83488   3900  1997 Tom DiCillo      Tom DiCillo   Matthew Modi…\n15        NA        NA   6400  1995 Theodoros Angel… Theodoros An… Harvey Keitel\n16  32000000  42059111  57000  2010 Nanette Burstein Geoff LaTuli… Drew Barrymo…\n17        NA   3741869   6100  1993 Kirk Wong        Tin Nam Chun  Jackie Chan  \n18        NA    124167   3600  1987 Alan Clarke      Andrea Dunbar Siobhan Finn…\n19  13000000  97837138 255000  2002 Joel Schumacher  Larry Cohen   Colin Farrell\n20   4800000 125479266 124000  2017 Christopher Lan… Scott Lobdell Jessica Rothe\n21        NA     83439   5900  2003 David Mickey Ev… David H. Ste… Erik von Det…\n22  75000000 107752036 163000  1999 David O. Russell John Ridley   George Cloon…\n23   3500000  27912072  54000  1993 Albert Hughes    Allen Hughes  Tyrin Turner \n24   4000000   4257354 100000  1995 Directors        Allison Ande… Tim Roth     \n25  11000000  59520298  19000  2012 Dustin Hoffman   Ronald Harwo… Maggie Smith \n26    100000    515900  19000  2001 Richard Linklat… Stephen Belb… Ethan Hawke  \n27  12000000  57968936  21000  1990 Dwight H. Little Michael Grais Steven Seagal\n28  50000000 152022101  43000  1995 Frank Marshall   Michael Cric… Laura Linney \n29  25000000  11212953  20000  2008 Kimberly Peirce  Mark Richard  Ryan Phillip…\n30  75000000 224012234 282000  1997 Simon West       Scott Rosenb… Nicolas Cage \n# ℹ 470 more rows\n# ℹ 2 more variables: company, country\n```\n\n\n:::\n:::\n\n:::\n\n\\end{landscape}\n\\clearpage\n````\n\n{{< pagebreak >}}\n\n# Part 2a - Score vs. runtime\n\nIn this part, we fit a model predicting `score` from `runtime` and name it `score_runtime_fit`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore_runtime_fit <- linear_reg() |>\n  fit(score ~ runtime, data = movies)\n```\n:::\n\n\n@fig-score-runtime visualizes the relationship between `score` and `runtime` as well as the linear model for predicting `score` from `runtime`. The top three movies in @tbl-data are labeled in the visualization as well. Answer all questions in this part based on @fig-score-runtime.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatterplot of `score` vs. `runtime` for `movies`.](midterm-2-practice_files/figure-html/fig-score-runtime-1.png){#fig-score-runtime width=624}\n:::\n:::\n\n\n## Question 7\n\nPartial code for producing @fig-score-runtime is given below. Which of the following goes in the blank on Line 2? **Select all that apply.**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"true\"}\nmovies |>\n  mutate(runtime = ___) |>\n  ggplot(aes(x = runtime, y = score)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = FALSE)\n  # additional code for annotating Blue City on the plot\n```\n:::\n\n\na.  `grepl(\" mins\", runtime)`\n\nb.  `grep(\" mins\", runtime)`\n\nc.  `str_remove(runtime, \" mins\")`\n\nd.  `as.numeric(str_remove(runtime, \" mins\"))`\n\ne.  `na.rm(runtime)`\n\n{{< pagebreak >}}\n\n## Question 8\n\nBased on this model, order the three labeled movies in @fig-score-runtime in decreasing order of the magnitude (absolute value) of their residuals.\n\na.  Winter Sleep\\> Rang De Basanti \\> Blue City\n\nb.  Winter Sleep\\> Blue City \\> Rang De Basanti\n\nc.  Rang De Basanti \\> Winter Sleep\\> Blue City\n\nd.  Blue City \\> Winter Sleep \\> Rang De Basanti\n\ne.  Blue City \\> Rang De Basanti \\> Winter Sleep\n\n\\vspace{2cm}\n\n## Question 9\n\n\n\nThe R-squared for the model visualized in @fig-score-runtime is 31%. Which of the following is the [**best**]{.underline} interpretation of this value?\n\na.  31% of the variability in movie runtimes is explained by their scores.\n\nb.  31% of the variability in movie scores is explained by their runtime.\n\nc.  The model accurately predicts scores of 31% of the movies in this sample.\n\nd.  The model accurately predicts scores of 31% of all movies.\n\ne.  The correlation between scores and runtimes of movies is 0.31.\n\n{{< pagebreak >}}\n\n# Part 2b - Score vs. runtime or year\n\nThe visualizations below show the relationship between `score` and `runtime` as well as `score` and `year`, respectively. Additionally, the lines of best fit are overlaid on the visualizations.\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](midterm-2-practice_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](midterm-2-practice_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::\n\n\nThe correlation coefficients of these relationships are calculated below, though some of the code and the output are missing. Answer all questions in this part based on the code and output shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmovies |>\n  __blank_1__(\n    r_score_runtime = cor(runtime, score),\n    r_score_year = cor(year, score)\n  )\n```\n:::\n\n\n```         \n# A tibble: 1 × 2\n  r_score_runtime r_score_year\n            <dbl>        <dbl>\n1           0.434. __blank_2__       \n```\n\n::: {layout=\"[0.5, 0.5]\"}\n::: {#firstcol}\n## Question 10\n\nWhich of the following goes in `__blank_1__`?\n\na.  `summarize`\n\nb.  `mutate`\n\nc.  `group_by`\n\nd.  `arrange`\n\ne.  `filter`\n:::\n\n::: {#secondcol}\n## Question 11\n\nWhat can we say about the value that goes in `__blank_2__`?\n\na.  `NA`\n\nb.  A value between 0 and 0.434.\n\nc.  A value between 0.434 and 1.\n\nd.  A value between 0 and -0.434.\n\ne.  A value between -1 and -0.434.\n:::\n:::\n\n{{< pagebreak >}}\n\n# Part 2c - Score vs. runtime and rating\n\nIn this part, we fit a model predicting `score` from `runtime` and `rating` (categorized as G, PG, PG-13, R, NC-17, and Not Rated), and name it `score_runtime_rating_fit`.\n\n\n::: {.cell}\n\n:::\n\n\nThe model output for `score_runtime_rating_fit` is shown in @tbl-score-runtime-rating-tidy. Answer all questions in this part based on @tbl-score-runtime-rating-tidy.\n\n\n::: {#tbl-score-runtime-rating-tidy .cell tbl-cap='Regression output for `score_runtime_rating_fit`.'}\n::: {.cell-output-display}\n\n\n|term            | estimate| std.error| statistic| p.value|\n|:---------------|--------:|---------:|---------:|-------:|\n|(Intercept)     |    4.525|     0.332|    13.647|   0.000|\n|runtime         |    0.021|     0.002|    10.702|   0.000|\n|ratingPG        |   -0.189|     0.295|    -0.642|   0.521|\n|ratingPG-13     |   -0.452|     0.292|    -1.547|   0.123|\n|ratingR         |   -0.257|     0.285|    -0.901|   0.368|\n|ratingNC-17     |   -0.355|     0.486|    -0.730|   0.466|\n|ratingNot Rated |   -0.282|     0.328|    -0.860|   0.390|\n\n\n:::\n:::\n\n\n\\vspace{1cm}\n\n## Question 12\n\nWhich of the following is [**TRUE**]{.underline} about the intercept of `score_runtime_rating_fit`? **Select all that are true.**\n\na.  Keeping runtime constant, G-rated movies are predicted to score, on average, 4.525 points.\n\nb.  Keeping runtime constant, movies without a rating are predicted to score, on average, 4.525 points.\n\nc.  Movies without a rating that are 0 minutes in length are predicted to score, on average, 4.525 points.\n\nd.  All else held constant, movies that are 0 minutes in length are predicted to score, on average, 4.525 points.\n\ne.  G-rated movies that are 0 minutes in length are predicted to score, on average, 4.525 points.\n\n{{< pagebreak >}}\n\n## Question 13\n\nWhich of the following is the [**best**]{.underline} interpretation of the slope of `runtime` in `score_runtime_rating_fit`?\n\na.  All else held constant, as runtime increases by 1 minute, the score of the movie increases by 0.021 points.\n\nb.  For G-rated movies, all else held constant, as runtime increases by 1 minute, the score of the movie increases by 0.021 points.\n\nc.  All else held constant, for each additional minute of runtime, movie scores will be higher by 0.021 points on average.\n\nd.  G-rated movies that are 0 minutes in length are predicted to score 0.021 points on average.\n\ne.  For each higher level of rating, the movie scores go up by 0.021 points on average.\n\n\\vspace{1.5cm}\n\n## Question 14\n\nFill in the blank:\n\n> R-squared for `score_runtime_rating_fit` (the model predicting `score` from `runtime` and `rating`) \\_\\_\\_\\_\\_\\_\\_\\_\\_ the R-squared the model `score_runtime_fit` (for predicting `score` from `runtime` alone).\n\na.  is less than\n\nb.  is equal to\n\nc.  is greater than\n\nd.  cannot be compared (based on the information provided) to\n\ne.  is both greater than and less than\n\n\\vspace{1.5cm}\n\n## Question 15\n\nThe model `score_runtime_rating_fit` (the model predicting `score` from `runtime` and `rating`) can be visualized as parallel lines for each level of `rating`. Which of the following is the equation of the line for R-rated movies?\n\na.  $\\widehat{score} = (4.525 - 0.257) + 0.021 \\times runtime$\n\nb.  $score = (4.525 - 0.257) + 0.021 \\times runtime$\n\nc.  $\\widehat{score} = 4.525 + (0.021 - 0.257) \\times runtime$\n\nd.  $score = 4.525 + (0.021 - 0.257) \\times runtime$\n\ne.  $\\widehat{score} = (4.525 + 0.021) - 0.257 \\times runtime$\n\n{{< pagebreak >}}\n\n# Part 3 - Miscellaneous\n\n## Question 16\n\nWhich of the following is the definition of a regression model? Select all that apply.\n\na\\. $\\hat{y} = b_0 + b_1 X_1$\n\nb\\. $y = \\beta_0 + \\beta_1 X_1$\n\nc\\. $\\hat{y} = \\beta_0 + \\beta_1 X_1 + \\epsilon$\n\nd\\. $y = \\beta_0 + \\beta_1 X_1 + \\epsilon$\n\n## Question 17\n\n**Choose the best answer.**\n\nA survey based on a random sample of 2,045 American teenagers found that a 95% confidence interval for the mean number of texts sent per month was (1450, 1550). A valid interpretation of this interval is\n\na.  95% of all teens who text send between 1450 and 1550 text messages per month.\nb.  If a new survey with the same sample size were to be taken, there is a 95% chance that the mean number of texts in the sample would be between 1450 and 1550.\nc.  We are 95% confident that the mean number of texts per month of all American teens is between 1450 and 1550.\nd.  We are 95% confident that, were we to repeat this survey, the mean number of texts per month of those taking part in the survey would be between 1450 and 1550.\n\n{{< pagebreak >}}\n\n## Question 18\n\nDefine the term \"parsimonious model\".\n\n::: {.content-visible when-format=\"pdf\"}\n$\\vspace{2cm}$\n:::\n\n# Part 4 - Building a spam filter\n\nThe data come from incoming emails in David Diez's (one of the authors of OpenIntro textbooks) Gmail account for the first three months of 2012. All personally identifiable information has been removed. The dataset is called `email` and it's in the **openintro** package.\n\nThe outcome variable is `spam`, which takes the value `1` if the email is spam, `0` otherwise.\n\n## Question 19\n\na.  What type of variable is `spam`?\n    What percent of the emails are spam?\n\nb.  What type of variable is `dollar` - number of times a dollar sign or the word “dollar” appeared in the email?\n    Visualize and describe its distribution, supporting your description with the appropriate summary statistics.\n\nc.  Fit a logistic regression model predicting `spam` from `dollar`.\n    Then, display the tidy output of the model.\n\nd.  Using this model and the `predict()` function, predict the probability the email is spam if it contains 5 dollar signs.\n    Based on this probability, how does the model classify this email?\n\n    ::: callout-note\n    To obtain the predicted probability, you can set the `type` argument in `predict()` to `\"prob\"`.\n    :::\n\n## Question 20\n\na.  Fit another logistic regression model predicting `spam` from `dollar`, `winner` (indicating whether “winner” appeared in the email), and `urgent_subj` (whether the word \"urgent\" is in the subject of the email).\n    Then, display the tidy output of the model.\n\nb.  Using this model and the `augment()` function, classify each email in the `email` dataset as spam or not spam.\n    Store the resulting data frame with an appropriate name and display the data frame as well.\n\nc.  Using your data frame from the previous part, determine, in a single pipeline, and using `count()`, the numbers of emails:\n\n    -   that are labelled as spam that are actually spam\n    -   that are not labelled as spam that are actually spam\n    -   that are labelled as spam that are actually not spam\n    -   that are not labelled as spam that are actually not spam\n\n    Store the resulting data frame with an appropriate name and display the data frame as well.\n\nd.  In a single pipeline, and using `mutate()`, calculate the false positive and false negative rates.\n    In addition to these numbers showing in your R output, you must write a sentence that explicitly states and identified the two rates.\n\n## Question 21\n\na.  Fit another logistic regression model predicting `spam` from `dollar` and another variable you think would be a good predictor.\n    Provide a 1-sentence justification for why you chose this variable.\n    Display the tidy output of the model.\n\nb.  Using this model and the `augment()` function, classify each email in the `email` dataset as spam or not spam.\n    Store the resulting data frame with an appropriate name and display the data frame as well.\n\nc.  Using your data frame from the previous part, determine, in a single pipeline, and using `count()`, the numbers of emails:\n\n    -   that are labelled as spam that are actually spam\n    -   that are not labelled as spam that are actually spam\n    -   that are labelled as spam that are actually not spam\n    -   that are not labelled as spam that are actually not spam\n\n    Store the resulting data frame with an appropriate name and display the data frame as well.\n\nd.  In a single pipeline, and using `mutate()`, calculate the false positive and false negative rates.\n    In addition to these numbers showing in your R output, you must write a sentence that explicitly states and identified the two rates.\n\ne.  Based on the false positive and false negatives rates of this model, comment, in 1-2 sentences, on which model (one from Question 20 or Question 21) is preferable and why.\n",
    "supporting": [
      "midterm-2-practice_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}