{
  "hash": "8d43debc52d5b47b5ba4cf3c0427d995",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear regression with a multiple predictors II\"\nsubtitle: \"Lecture 15\"\ndate: \"2025-03-18\"\nformat: revealjs\nauto-stretch: false\n---\n\n# Quick announcements\n\n## While you wait... \n\n\n::: {.cell}\n\n:::\n\n\n::: appex\n-   Go to your `ae` project in RStudio.\n\n-   Make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   Click Pull to get today's application exercise file: *ae\\-12\\-modeling\\-loans\\.qmd*.\n\n-   Wait till the you're prompted to work on the application exercise during class before editing the file.\n:::\n\n## Mid-semester evaluation\n\nPlease complete this ungraded, anonymous Canvas quiz before Wednesday night:\n\n[https://canvas.duke.edu/courses/50057/quizzes/30407](https://canvas.duke.edu/courses/50057/quizzes/30407)\n\n\n## SSMU Bookbagging GBM Saturday March 22! {.scrollable}\n\n::: columns\n::: {.column width=\"50%\"}\n![](images/15/flyer_image_upload_4627193_SSMUGBMMarchFlyer_317134538.png){fig-align=\"center\"}\n:::\n\n::: {.column width=\"50%\"}\n\nGrab free food and chat with upperclass students about...\n\n- course registration\n- the stats major\n- DataFest\n- volunteering\n:::\n:::\n\n## Project clarifications\n\n- **Next Monday**: your TA returns proposal feedback to you;\n\n- **Until then**: project repos are locked (can't push or pull);\n\n- If you missed milestone 1, we'll replace that score with your final peer eval score (so pull your weight!);\n\n- We will drop one of the first three peer evals;\n\n- If your group does not have plans to meet every week...make them!\n\n\n# Recap: simple linear regression\n\n## Question: how do we concisely summarize the association between two variables? {.scrollable}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Answer: simple linear regression! {.scrollable}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Answer: simple linear regression! {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg_wt_fit <- linear_reg() |>\n  fit(mpg ~ wt, data = mtcars)\n\ntidy(mpg_wt_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    37.3      1.88      19.9  8.24e-19\n2 wt             -5.34     0.559     -9.56 1.29e-10\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{mpg}=37.3 - 5.34\\times weight.\n$$\n\n**Interpretations**\n\n-   We predict that a car weighing zero pounds will have 37.28 MPG on average (makes no sense);\n-   We predict that a 1000 pound increase in weight in associated with a 5.34 decrease in MGP, on average.\n\n## Why do we care? Prediction!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## Why do we care? Prediction!\n\nYou can use the fitted model to generate predictions for yet-to-be-observed subjects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_car <- tibble(\n  wt = 4.5\n)\n\npredict(mpg_wt_fit, new_data = new_car)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  13.2\n```\n\n\n:::\n:::\n\n\n# Before break: multiple linear regression\n\n## Simple linear regression for those darn penguins\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n## How do we predict using more than one predictor?\n\nBoth of these models use `flipper_length_mm` *and* `island` to predict `body_mass_g`:\n\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/additive-interaction-viz-1.png){width=960}\n:::\n\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/additive-interaction-viz-2.png){width=960}\n:::\n:::\n\n\n## The additive model: parallel lines, one for each island\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm + island, data = penguins)\n\ntidy(bm_fl_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)        -4625.     392.      -11.8  4.29e-27\n2 flipper_length_mm     44.5      1.87     23.9  1.65e-74\n3 islandDream         -262.      55.0      -4.77 2.75e- 6\n4 islandTorgersen     -185.      70.3      -2.63 8.84e- 3\n```\n\n\n:::\n:::\n\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n## Where do the three lines come from? {.scrollable}\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length \\\\\n&- 262 \\times Dream \\\\\n&- 185 \\times Torgersen\n\\end{aligned}\n$$\n\n. . .\n\nIf penguin is from Biscoe, Dream = 0 and Torgersen = 0:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4625 &+ 44.5 \\times flipper~length\n\\end{aligned}\n$$\n\n. . .\n\nIf penguin is from Dream, Dream = 1 and Torgersen = 0:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4887 &+ 44.5 \\times flipper~length\n\\end{aligned}\n$$\n\n. . .\n\nIf penguin is from Torgersen, Dream = 0 and Torgersen = 1:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -4810 &+ 44.5 \\times flipper~length\n\\end{aligned}\n$$\n\n. . .\n\nEither way, same slope, so the lines are parallel.\n\n## The interaction model: different lines for each island {.medium .scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_island_int_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm * island, data = penguins)\n\ntidy(bm_fl_island_int_fit) |> select(term, estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  term                              estimate\n  <chr>                                <dbl>\n1 (Intercept)                        -5464. \n2 flipper_length_mm                     48.5\n3 islandDream                         3551. \n4 islandTorgersen                     3218. \n5 flipper_length_mm:islandDream        -19.4\n6 flipper_length_mm:islandTorgersen    -17.4\n```\n\n\n:::\n:::\n\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length \\\\\n&+ 3551 \\times Dream \\\\\n&+ 3218 \\times Torgersen \\\\\n&- 19.4 \\times flipper~length*Dream \\\\\n&- 17.4 \\times flipper~length*Torgersen\n\\end{aligned}\n$$\n\n## Where do the three lines come from? {.medium .scrollable}\n\n$$\n\\begin{aligned}\n\\small\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length \\\\\n&+ 3551 \\times Dream \\\\\n&+ 3218 \\times Torgersen \\\\\n&- 19.4 \\times flipper~length*Dream \\\\\n&- 17.4 \\times flipper~length*Torgersen\n\\end{aligned}\n$$\n\n. . .\n\nIf penguin is from Biscoe, Dream = 0 and Torgersen = 0:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} = -5464 &+ 48.5 \\times flipper~length\n\\end{aligned}\n$$\n\n. . .\n\nIf penguin is from Dream, Dream = 1 and Torgersen = 0:\n\n. . .\n\n$$\n\\begin{aligned}\n\\widehat{body~mass} &= (-5464 + 3551) + (48.5-19.4) \\times flipper~length\\\\\n&=-1913+29.1\\times flipper~length.\n\\end{aligned}\n$$\n\n## Prediction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguin <- tibble(\n  flipper_length_mm = 200,\n  island = \"Torgersen\"\n)\n\npredict(bm_fl_island_int_fit, new_data = new_penguin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 3980.\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{body~mass} = (-5464 + 3218) + (48.5-17.4) \\times 200.\n$$\n\n## Multiple numerical predictors {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_fl_bl_fit <- linear_reg() |>\n  fit(body_mass_g ~ flipper_length_mm + bill_length_mm, data = penguins)\n\ntidy(bm_fl_bl_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term              estimate std.error statistic  p.value\n  <chr>                <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)       -5737.      308.      -18.6  7.80e-54\n2 flipper_length_mm    48.1       2.01     23.9  7.56e-75\n3 bill_length_mm        6.05      5.18      1.17 2.44e- 1\n```\n\n\n:::\n:::\n\n\n. . .\n\n$$\n\\small\\widehat{body~mass}=-5736+48.1\\times flipper~length+6\\times bill~length\n$$\n\n. . .\n\n**Interpretations**: \n\n::: incremental\n- We predict that the body mass of a penguin with *zero* flipper length and *zero* bill length will be -5736 grams, on average (**makes no sense**);\n- Holding all other variables constant, for every additional millimeter in flipper length, we expect the body mass of penguins to be higher, on average, by 48.1 grams.\n- Holding all other variables constant, for every additional millimeter in bill length, we expect the body mass of penguins to be higher, on average, by 6 grams.\n:::\n\n## Prediction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguin <- tibble(\n  flipper_length_mm = 200,\n  bill_length_mm = 45\n)\n\npredict(bm_fl_bl_fit, new_data = new_penguin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4164.\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{body~mass}=-5736+48.1\\times 200+6\\times 45\n$$\n\n## Picture? It's not pretty...\n\n2 predictors + 1 response = 3 dimensions. Ick!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n## Picture? It's not pretty...\n\nInstead of a line of best fit, it's a *plane* of best fit. Double ick!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](15-linear-model-multiple-predictors-II_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## ae\\-12\\-modeling\\-loans\n\n::: appex\n-   Go to your ae project in RStudio.\n\n-   If you haven't yet done so, make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   If you haven't yet done so, click Pull to get today's application exercise file: *ae\\-12\\-modeling\\-loans\\.qmd*.\n\n-   Work through the application exercise in class, and render, commit, and push your edits.\n:::",
    "supporting": [
      "15-linear-model-multiple-predictors-II_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}