{
  "hash": "aabb0d71734984c89a5771058e1603ad",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Recap: simple linear regression\"\nsubtitle: \"Lab 5\"\ndate: \"2025-03-17\"\nformat: revealjs\nauto-stretch: false\n---\n\n \n# Simple linear regression\n\n## Question: how do we concisely summarize the association between two variables? {.scrollable}\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab-5_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Answer: simple linear regression! {.scrollable}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab-5_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Answer: simple linear regression! {.scrollable}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg_wt_fit <- linear_reg() |>\n  fit(mpg ~ wt, data = mtcars)\n\ntidy(mpg_wt_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    37.3      1.88      19.9  8.24e-19\n2 wt             -5.34     0.559     -9.56 1.29e-10\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{mpg}=37.3 - 5.34\\times weight.\n$$\n\n**Interpretations**\n\n- We predict that a car weighing zero pounds will have 37.28 MPG on average (makes no sense);\n- We predict that a 1000 pound increase in weight in associated with a 5.34 decrease in MGP, on average.\n\n## Why do we care? Prediction!\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab-5_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n## Why do we care? Prediction!\n\nYou can use the fitted model to generate predictions for yet-to-be-observed subjects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_car <- tibble(\n  wt = 3.5\n)\n\npredict(mpg_wt_fit, new_data = new_car)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  18.6\n```\n\n\n:::\n:::\n\n\n# Part 1 of today's lab...\n\n## Does increasing the minimum wage decrease employment? {.scrollable}\n\n- This is a hotly debated question in economics and public policy;\n\n- ECON 101 logic says that it might: if you make something more expensive (employing people), people do less of it.\n\n- **What do the actual data say?**\n\n## Classic study: Card and Krueger (1994 AER) {.scrollable}\n\n- In 1992, NJ raised minimum wage. PA did not;\n\n- Fast-food restaurants along the NJ/PA border are probably very similar. Maybe the only difference is the change in wage policy;\n\n- So PA is like *control* and NJ is like the *treatment*;\n\n- If we compare employment before and after the policy change, maybe we can give the observed differences a **causal** interpretation. The increase in minimum wage caused employment to go up, down, or stay the same;\n\n- This is called a **natural experiment**. It's a kind of observational study where you get *very* lucky and \"nature\" does the experimental control for you.\n\n## Classic study: Card and Krueger (1994 AER) {.scrollable}\n\n![](images/labs/card-krueger.jpg)\n",
    "supporting": [
      "lab-5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}