{
  "hash": "e4ec6e4c2dcfa0cfe9f78c058427b315",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AE 20: A Dataset's Life\"\nexecute:\n  warning: false\n  message: false\n---\n\n[![](images/airplane-joke.webp){fig-align=\"center\" width=\"75%\"}](https://en.wikipedia.org/wiki/Airplane!)\n\nNope, it's not [A Hero's Life](https://youtu.be/0QsaPvrT-40?feature=shared), or A Boy's Life, or A Nun's Life; it's A Dataset's Life. Let's take a data set through all four steps in our data science workflow:\n\n1.  **preparation**: import, join, clean, reshape, mutate, etc;\n2.  **exploration**: pictures (ABV!) and a concise set of numerical summaries;\n3.  **modeling**: linear/logistic regression, model selection, etc;\n4.  **inference**: interval estimation and hypothesis testing.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n```\n:::\n\n\nIf you're like me, you are sick of the penguins at this point. So for our last act, let's banish them to worlds beyond. I packed all of those lil' beasts onto a rocket ship and took them to both Mars and Venus, where I recorded their weights (in pounds). I then abandoned the ship to hurtle through space so that future stawanana students never have to study them again.\n\n# 1. Preparation\n\n## Load the data\n\nI have two sets of measurements for the same sample of penguins: one set taken on Mars, and another on Venus. They are contained in two separate files that need to be merged:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_venus <- read_csv(\"data/penguins_venus.csv\")\npenguins_mars <- read_csv(\"data/penguins_mars.csv\")\n\nglimpse(penguins_venus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 6\n$ id                <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1…\n$ species           <chr> \"Adelie\", \"Adelie\", \"Adelie\", \"Adelie\", \"Adelie\", \"A…\n$ island            <chr> \"Torgersen\", \"Torgersen\", \"Torgersen\", \"Torgersen\", …\n$ sex               <chr> \"male\", \"female\", \"female\", NA, \"female\", \"male\", \"f…\n$ flipper_length_mm <dbl> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ weight_lb         <dbl> 8.356999, 7.347528, 6.165162, NA, 9.173660, 8.157105…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(penguins_mars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 2\n$ id        <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ weight_lb <chr> \"3.8219301852578837\", \"3.56777681688403\", \"1.761707536468984…\n```\n\n\n:::\n:::\n\n\n## Merge the data\n\n**Task**: Use an appropriate `join` function to create a new data frame called `space_penguins`, where each penguin's weight on either planet is recorded in a separate column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins <- full_join(penguins_venus, penguins_mars, by = join_by(id)) |>\n  rename(venus_weight = weight_lb.x,\n         mars_weight = weight_lb.y)\nspace_penguins\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 344 × 7\n      id species island    sex    flipper_length_mm venus_weight mars_weight    \n   <dbl> <chr>   <chr>     <chr>              <dbl>        <dbl> <chr>          \n 1     1 Adelie  Torgersen male                 181         8.36 3.821930185257…\n 2     2 Adelie  Torgersen female               186         7.35 3.567776816884…\n 3     3 Adelie  Torgersen female               195         6.17 1.761707536468…\n 4     4 Adelie  Torgersen <NA>                  NA        NA    <NA>           \n 5     5 Adelie  Torgersen female               193         9.17 3.073547356370…\n 6     6 Adelie  Torgersen male                 190         8.16 2.026601878680…\n 7     7 Adelie  Torgersen female               181         8.58 3.318306212723…\n 8     8 Adelie  Torgersen male                 195        11.9  3.772687060633…\n 9     9 Adelie  Torgersen <NA>                 193         8.14 2.603709532256…\n10    10 Adelie  Torgersen <NA>                 190         8.10 3.002844015041…\n# ℹ 334 more rows\n```\n\n\n:::\n:::\n\n\n## Reshape the data\n\n**Task**: Use an appropriate `pivot` function to create a new version of `space_penguins` where the information about the planet where the measurements were taken is its own column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins_long <- space_penguins |>\n  pivot_longer(\n    cols = c(venus_weight, mars_weight),\n    names_to = \"planet\",\n    values_to = \"weight_lb\"\n  )\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `pivot_longer()`:\n! Can't combine `venus_weight` <double> and `mars_weight` <character>.\n```\n\n\n:::\n:::\n\n\nWoops! Looks like we might have a problem here. Why is it saying that the Mars weights are type character?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins |>\n  select(mars_weight) |>\n  arrange(desc(mars_weight))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 344 × 1\n   mars_weight                          \n   <chr>                                \n 1 this is why we can't have nice things\n 2 get wrecked                          \n 3 6.93005873361171                     \n 4 6.233851410442386                    \n 5 6.151607146997191                    \n 6 6.054400666505051                    \n 7 6.021791903417968                    \n 8 6.010224782201169                    \n 9 5.99589305540989                     \n10 5.844409564530165                    \n# ℹ 334 more rows\n```\n\n\n:::\n:::\n\n\nOh. That's really stupid. If we tell it to convert this column to numbers, it will do it, and anything it cannot convert (such as those two pieces of text) will simply be replaced with `NA`, which is fine by me in this case:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins <- space_penguins |>\n  mutate(\n    mars_weight = as.numeric(mars_weight)\n  )\n\nspace_penguins\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 344 × 7\n      id species island    sex    flipper_length_mm venus_weight mars_weight\n   <dbl> <chr>   <chr>     <chr>              <dbl>        <dbl>       <dbl>\n 1     1 Adelie  Torgersen male                 181         8.36        3.82\n 2     2 Adelie  Torgersen female               186         7.35        3.57\n 3     3 Adelie  Torgersen female               195         6.17        1.76\n 4     4 Adelie  Torgersen <NA>                  NA        NA          NA   \n 5     5 Adelie  Torgersen female               193         9.17        3.07\n 6     6 Adelie  Torgersen male                 190         8.16        2.03\n 7     7 Adelie  Torgersen female               181         8.58        3.32\n 8     8 Adelie  Torgersen male                 195        11.9         3.77\n 9     9 Adelie  Torgersen <NA>                 193         8.14        2.60\n10    10 Adelie  Torgersen <NA>                 190         8.10        3.00\n# ℹ 334 more rows\n```\n\n\n:::\n:::\n\n\nAlright, let's try to reshape again:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins_long <- space_penguins |>\n  pivot_longer(\n    cols = c(venus_weight, mars_weight),\n    names_to = \"planet\",\n    values_to = \"weight_lb\"\n  ) |>\n  mutate(\n    planet = if_else(planet == \"venus_weight\", \"Venus\", \"Mars\")\n  )\nspace_penguins_long\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 688 × 7\n      id species island    sex    flipper_length_mm planet weight_lb\n   <dbl> <chr>   <chr>     <chr>              <dbl> <chr>      <dbl>\n 1     1 Adelie  Torgersen male                 181 Venus       8.36\n 2     1 Adelie  Torgersen male                 181 Mars        3.82\n 3     2 Adelie  Torgersen female               186 Venus       7.35\n 4     2 Adelie  Torgersen female               186 Mars        3.57\n 5     3 Adelie  Torgersen female               195 Venus       6.17\n 6     3 Adelie  Torgersen female               195 Mars        1.76\n 7     4 Adelie  Torgersen <NA>                  NA Venus      NA   \n 8     4 Adelie  Torgersen <NA>                  NA Mars       NA   \n 9     5 Adelie  Torgersen female               193 Venus       9.17\n10     5 Adelie  Torgersen female               193 Mars        3.07\n# ℹ 678 more rows\n```\n\n\n:::\n:::\n\n\nSo, we have the wide view in `space_penguins`, where each row is a penguin, and we have the long view in `space_penguins_long` where each row is a penguin/planet. Which of these is \"tidy\"? As we will see, it depends on the task.\n\n# 2. Exploration\n\n## Pictures\n\n**Task**: Generate side-by-side density plots of the weights on each planet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(space_penguins_long, aes(x = weight_lb, fill = planet)) + \n  geom_density(alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nSo, weights on Mars are systematically lower than weights on Venus.\n\nIf we wished to slice-and-dice the data further according to other categorical variables like `sex` or `island`, we could do it with one of those darned `facet` functions (I can never remember which is which or where the `~` goes):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(space_penguins_long, aes(x = weight_lb, fill = planet)) + \n  geom_density(alpha = 0.5) + \n  facet_grid(island ~ .)\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## A concise set of numerical summaries\n\n**Task**: compute the mean, standard deviation, and median of weight on each planet:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins_long |>\n  group_by(planet) |>\n  summarize(\n    mean_wt = mean(weight_lb, na.rm = TRUE),\n    sd_wt = sd(weight_lb, na.rm = TRUE),\n    med_wt = median(weight_lb, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  planet mean_wt sd_wt med_wt\n  <chr>    <dbl> <dbl>  <dbl>\n1 Mars      3.58  1.19   3.62\n2 Venus     8.46  1.94   8.36\n```\n\n\n:::\n:::\n\n\nNotice that these numbers match what we saw in the plot. The distributions are symmetric, and so the means and medians are about the same. Furthermore, the spread of the Mars distribution was lower than the spread of the Venus distribution, and we see that in the numbers as well.\n\n# 3. Modeling\n\nWhat is the conversion factor between weights on Venus and weights on Mars? If you ask a physicist, I'm pretty sure they will tell you it's this:\n\n$$\nMars~weight~(lb)\\approx Venus~weight~(lb)\\times 0.41.\n$$\n\nSo, you weigh less on Mars than you do on Venus. Something something gravity. If we didn't already know this, could we learn it from our data? Note that is is not a foregone conclusion, because our data are *noisy*. The weights have been measured *with error*, and so what should be a perfect straight line relationship won't be, exactly.\n\n## Linear\n\n**Task**: Create a scatterplot of **Venus weights versus Mars weights**, and add a line of best fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(space_penguins, aes(x = venus_weight, y = mars_weight)) + \n  geom_point() + \n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n::: callout-warning\n## Plotting \"this\" versus \"that\"\n\nThere has been some controversy about how to read a phrase like \"Venus weights versus Mars weights.\" I personally take it to mean that Venus weights go on the $x$-axis and Mars weights go on the $y$-axis, but some on the teaching team think I am psychotic for thinking this. Based on my informal polling of students, we all would seem to be evenly split on this point. Anyway, you're not being tested on this, and on an exam I will try to be sufficiently clear so that it doesn't end up mattering.\n:::\n\n**Task**: Compute and interpret the estimated slope and intercept of the best fit line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_fit <- linear_reg() |>\n  fit(mars_weight ~ venus_weight, data = space_penguins)\n\ntidy(linear_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     1.17     0.256       4.57 6.80e- 6\n2 venus_weight    0.285    0.0295      9.68 1.02e-19\n```\n\n\n:::\n:::\n\n\n$$\n\\widehat{Mars~weight} = 1.17 + 0.28\\times Venus~weight\n$$\n\n**Interpretations**:\n\n-   **intercept**: if a penguin weighs zero pounds on Venus, we predict that, on average, they weigh 1.17 pounds on Mars. This obviously makes no sense;\n-   **slope**: a one pound increase on Venus predicts a 0.28 pounds increase on Mars, on average.\n\nHmmm. We know that the \"true\" relationship has an intercept of 0 and a slope of 0.41, so this is not so good.\n\n::: {.callout-note collapse=\"true\"}\n## Don't read this. You don't need to know this.\n\nWhat we're witnessing here is [*attenuation bias*](https://en.wikipedia.org/wiki/Regression_dilution).\n:::\n\n## Logistic\n\n**Task**: fit a logistic regression that predicts the planet the measurement was made on from the value of the measurement. Lower measurements were probably more likely to have been taken on Mars, as we saw.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspace_penguins_long <- space_penguins_long |>\n  mutate(planet = as_factor(planet))\n\nlevels(space_penguins_long$planet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Venus\" \"Mars\" \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogistic_fit <- logistic_reg() |>\n  fit(planet ~ weight_lb, data = space_penguins_long)\n\ntidy(logistic_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    14.4      1.51       9.53 1.50e-21\n2 weight_lb      -2.60     0.277     -9.39 5.86e-21\n```\n\n\n:::\n:::\n\n\n$$\n\\log\\left(\\frac{\\hat{p}}{1-\\hat{p}}\\right)=14.4-2.6\\times weight\n$$\n\n**Interpretations**:\n\n-   **intercept**: we predict a weight measurement of zero lb to have come from the planet Mars with an odds of $e^{14.4}\\approx 1794075$. Again, doesn't make a tremendous amount of sense, but in general, the lower the weight, the more likely it was to have been recorded on Mars;\n-   **slope**: for each one pound increase in the measurement, we predict on average that the odds of the measurement coming from Mars decrease by a multiplicative factor of $e^{-2.6}\\approx 0.074$. That is precipitous!\n\n**Task**: generate the ROC curve for this model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_aug <- augment(logistic_fit, space_penguins_long)\n\nlog_roc <- roc_curve(log_aug, \n                     truth = planet, \n                     .pred_Mars, \n                     event_level = \"second\")\n\nggplot(log_roc, aes(x = 1 - specificity, y = sensitivity)) +\n  geom_path() +\n  geom_abline(lty = 3) +\n  coord_equal() + \n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nSo, given a measurement, it's not too hard to predict what planet it was taken on. Our model does a pretty good job.\n\n# 4. Inference\n\nBack to linear regression now...\n\n## Interval estimation\n\n**Task**: Compute, visualize, and interpret a 95% confidence interval for the slope of the regression line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_fit <- space_penguins |>\n  specify(mars_weight ~ venus_weight) |>\n  fit()\n\nset.seed(8675309)\nboot_fits <- space_penguins |>\n  specify(mars_weight ~ venus_weight) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  fit()\n\nci_95 <- get_confidence_interval(\n  boot_fits,\n  point_estimate = observed_fit,\n  level = 0.95,\n  type = \"percentile\"\n)\nci_95\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  term         lower_ci upper_ci\n  <chr>           <dbl>    <dbl>\n1 intercept       0.654    1.69 \n2 venus_weight    0.228    0.342\n```\n\n\n:::\n\n```{.r .cell-code}\nvisualize(boot_fits) + \n  shade_confidence_interval(ci_95)\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nWe are 95% confident that the true slope is between 0.228 and 0.342. \n\n## Hypothesis testing\n\n**Task**: Test the following hypotheses at the 5% level:\n\n$$\n\\begin{aligned}\nH_0&:\\beta_1=0\\\\\nH_A&:\\beta_1\\neq0\n\\end{aligned}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(20)\nnull_dist <- space_penguins |>\n  specify(mars_weight ~ venus_weight) |>\n  hypothesize(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  fit()\n\nvisualize(null_dist) +\n  shade_p_value(obs_stat = observed_fit, direction = \"two-sided\")\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\nnull_dist |>\n  get_p_value(obs_stat = observed_fit, direction = \"two-sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  term         p_value\n  <chr>          <dbl>\n1 intercept          0\n2 venus_weight       0\n```\n\n\n:::\n:::\n\n\nThe p-value is basically zero. This means that, in a world where the null hypothesis is true, and $\\beta_1$ does in fact equal zero, then there is a 0% chance that we would observe an estimated slope as or more extreme than the one we saw. This provides evidence that the null is totally bogus, and so we reject it. \n\n**Task**: Test the following hypotheses at the 5% level:\n\n$$\n\\begin{aligned}\nH_0&:\\beta_1=0.41\\\\\nH_A&:\\beta_1\\neq0.41\n\\end{aligned}\n$$\n\nWe haven't exactly learned how to do this, but there's a duality between confidence intervals and hypothesis testing. Determining how far the estimate is in the tails of the null distribution is the same as determining whether or not the hypothesized value is contained in a confidence interval. Our 95% confidence interval was (0.228, 0.342). This **does not** contain the hypothesized value of 0.41, meaning that the hypothesized value is not within the range of likely values. So we reject the null at the 5% level (because it was a 95% interval). \n\n::: callout-note\n## Reality check\nThis is a setting where we sorta know the true value. Physicists are pretty sure the slope is 0.41, so it's alarming that we just rejected that hypothesis. What's a boy to do?\n:::\n\n# BONUS: regression through the origin\n\nThis is the (population) linear model we are estimating with data:\n\n$$\nMars~weight = \\beta_0+\\beta_1\\times Venus~weight + \\varepsilon.\n$$\n\nSo we are allowing for the possibility that $\\beta_0\\neq 0$ even though we know this is logically impossible. If the weight on Venus is zero, then the weight on Mars for the same subject must also be zero. Period. \n\nIf we wish to *force* the intercept to be zero to align with this logic, then we are using the **regression-through-the-origin** model:\n\n$$\nMars~weight = \\beta_1\\times Venus~weight + \\varepsilon.\n$$\n\nWe still estimate $\\beta_1$ using least squares, but now we're getting the best fitting line that goes through the origin, as opposed to the best fitting line that could go anywhere.\n\nThis is how to fit this in `R`. That `-1` syntax is like saying \"remove the intercept.\" \n\n\n::: {.cell}\n\n```{.r .cell-code}\nbetter_fit <- linear_reg() |>\n  fit(mars_weight ~ venus_weight - 1, data = space_penguins)\n\ntidy(better_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  term         estimate std.error statistic   p.value\n  <chr>           <dbl>     <dbl>     <dbl>     <dbl>\n1 venus_weight    0.417   0.00678      61.5 6.26e-186\n```\n\n\n:::\n:::\n\n\nHey good lookin', what's cookin'! That's a number I like. So, when we use some *domain knowledge* to change the model and force it to better match how reality works, we get better results. Here's how the previous line of best fit and the best-fit-through-the-origin line compare:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(space_penguins, aes(x = venus_weight, y = mars_weight)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE) + \n  geom_smooth(method = \"lm\", se = FALSE, formula = y ~ x - 1, color = \"red\") + \n  xlim(0, 14) + \n  ylim(0, 7)\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nIf we redo the confidence interval for the slope in this new model, the \"true value\" is comfortably inside:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_fit <- space_penguins |>\n  specify(mars_weight ~ venus_weight - 1) |>\n  fit()\n\nset.seed(8675309)\nboot_fits <- space_penguins |>\n  specify(mars_weight ~ venus_weight - 1) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  fit()\n\nci_90 <- get_confidence_interval(\n  boot_fits,\n  point_estimate = observed_fit,\n  level = 0.95,\n  type = \"percentile\"\n)\nci_90\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  term         lower_ci upper_ci\n  <chr>           <dbl>    <dbl>\n1 venus_weight    0.404    0.430\n```\n\n\n:::\n\n```{.r .cell-code}\nvisualize(boot_fits) + \n  shade_confidence_interval(ci_90)\n```\n\n::: {.cell-output-display}\n![](ae-20-final-review_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nFab.\n",
    "supporting": [
      "ae-20-final-review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}