{
  "hash": "74cebc4f4b9fbb9b82835601e75a1058",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Midterm 2 Practice Answers\nexecute:\n  echo: false\n---\n\n1.  \\(c\\) For every additional \\$1,000 of annual salary, the model predicts the raise to be higher, on average, by 0.0155%.\n2.  \\(d\\) $R^2$ of `raise_2_fit` is higher than $R^2$ of `raise_1_fit` since `raise_2_fit` has one more predictor and $R^2$ always\n3.  The reference level of `performance_rating` is High, since it’s the first level alphabetically. Therefore, the coefficient -2.40% is the predicted difference in raise comparing High to Successful. In this context a negative coefficient makes sense since we would expect those with High performance rating to get higher raises than those with Successful performance.\n4.  \\(a\\) “Poor”, “Successful”, “High”, “Top”.\n5.  Option 3. It's a linear model with no interaction effect, so parallel lines. And since the slope for `salary_typeSalaried` is positive, its intercept is higher. The equations of the lines are as follows:\n    -   Hourly:\n\n        $$\n        \\begin{align*}\n        \\widehat{percent\\_incr} &= 1.24 + 0.0000137 \\times annual\\_salary + 0.913 salary\\_typeSalaried \\\\\n        &= 1.24 + 0.0000137 \\times annual\\_salary + 0.913 \\times 0 \\\\\n        &= 1.24 + 0.0000137 \\times annual\\_salary\n        \\end{align*}\n        $$\n\n    -   Salaried:\n\n        $$\n        \\begin{align*}\n        \\widehat{percent\\_incr} &= 1.24 + 0.0000137 \\times annual\\_salary + 0.913 salary\\_typeSalaried \\\\\n        &= 1.24 + 0.0000137 \\times annual\\_salary + 0.913 \\times 1 \\\\\n        &= 2.153 + 0.0000137 \\times annual\\_salary\n        \\end{align*}\n        $$\n6.  \\(c\\) The model predicts that the percentage increase employees with Successful performance get, on average, is higher by a factor of 1025 compared to the employees with Poor performance rating.\n7.  \\(d\\) `as.numeric(str_remove(runtime, \" mins\"))`\n8.  \\(e\\) Blue City $>$ Rang De Basanti $>$ Winter Sleep\n9.  \\(b\\) 31% of the variability in movie scores is explained by their runtime.\n10. \\(a\\) summarize\n11. \\(b\\) A value between 0 and 0.434.\n12. \\(e\\) G-rated movies that are 0 minutes in length are predicted to score, on average, 4.525 points.\n13. \\(c\\) All else held constant, for each additional minute of runtime, movie scores will be higher by 0.021 points on average.\n14. \\(c\\) is greater than\n15. \\(a\\) $\\widehat{score} = (4.525 - 0.257) + 0.021 \\times runtime$\n16. \\(a\\) and (d).\n17. \\(c\\) We are 95% confident that the mean number of texts per month of all American teens is between 1450 and 1550.\n18. A parsimonious model is the simplest model with the best predictive performance.\n19. \na.\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\n```\n:::\n\n\nSpam is a factor; it is an indicator for if an email was spam or not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemail |> \n  count(spam) |>\n  mutate(percent = (n/sum(n))*100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  spam      n percent\n  <fct> <int>   <dbl>\n1 0      3554   90.6 \n2 1       367    9.36\n```\n\n\n:::\n:::\n\n\nAbout 9.36 percent of the emails are labeled spam.\n\nb.\\\nDollar is a double.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemail |>\n  ggplot(aes(x = dollar)) + \n  geom_histogram(bins = 20) + \n  labs(\n    title = \"Histogram of dollar mentions in emails\",\n    x = \"Number of times dollar appears in the email\",\n    y = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](midterm-2-practice-solns_files/figure-html/dollar-distribution-1.png){width=672}\n:::\n\n```{.r .cell-code}\nemail |>\n  summarize(\n    dollar_median = median(dollar),\n    dollar_iqr = IQR(dollar),\n    dollar_q25 = quantile(dollar, 0.25),\n    dollar_q75 = quantile(dollar, 0.75)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  dollar_median dollar_iqr dollar_q25 dollar_q75\n          <dbl>      <dbl>      <dbl>      <dbl>\n1             0          0          0          0\n```\n\n\n:::\n:::\n\n\nThe distribution of `dollar` is unimodal and right-skewed with a median of 0. In fact, the majority of the emails have 0 dollar signs in them.\n\nc.\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspam_dollar_fit <- logistic_reg() |>\n  fit(spam ~ dollar, data = email)\n\ntidy(spam_dollar_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)  -2.21      0.0569    -38.9  0      \n2 dollar       -0.0564    0.0195     -2.89 0.00380\n```\n\n\n:::\n:::\n\n\nd.\\\n\nThe probability the email is spam in this case is 7.6%. Since it is less than 50% the email is classified as not spam.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_email = tibble(dollar = 5)\n\npredict(spam_dollar_fit, new_data = new_email, type = \"prob\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  .pred_0 .pred_1\n    <dbl>   <dbl>\n1   0.924  0.0763\n```\n\n\n:::\n:::\n\n\n20. \na\\.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspam_dollar_winner_urg_fit <- logistic_reg() |>\n  fit(\n    spam ~ dollar + winner + urgent_subj, \n    data = email\n  )\n\ntidy(spam_dollar_winner_urg_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   -2.26      0.0581    -38.9  0       \n2 dollar        -0.0663    0.0195     -3.40 6.86e- 4\n3 winneryes      1.78      0.287       6.21 5.21e-10\n4 urgent_subj1   2.61      0.767       3.40 6.75e- 4\n```\n\n\n:::\n:::\n\n\nb\\.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspam_dollar_winner_urg_aug <- augment(spam_dollar_winner_urg_fit, new_data = email)\n\nspam_dollar_winner_urg_aug\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,921 × 24\n   .pred_class .pred_0 .pred_1 spam  to_multiple from     cc sent_email\n   <fct>         <dbl>   <dbl> <fct> <fct>       <fct> <int> <fct>     \n 1 0             0.906  0.0944 0     0           1         0 0         \n 2 0             0.906  0.0944 0     0           1         0 0         \n 3 0             0.926  0.0740 0     0           1         0 0         \n 4 0             0.906  0.0944 0     0           1         0 0         \n 5 0             0.906  0.0944 0     0           1         0 0         \n 6 0             0.906  0.0944 0     0           1         0 0         \n 7 0             0.906  0.0944 0     1           1         0 1         \n 8 0             0.906  0.0944 0     1           1         1 1         \n 9 0             0.906  0.0944 0     0           1         0 0         \n10 0             0.906  0.0944 0     0           1         0 0         \n# ℹ 3,911 more rows\n# ℹ 16 more variables: time <dttm>, image <dbl>, attach <dbl>, dollar <dbl>,\n#   winner <fct>, inherit <dbl>, viagra <dbl>, password <dbl>, num_char <dbl>,\n#   line_breaks <int>, format <fct>, re_subj <fct>, exclaim_subj <dbl>,\n#   urgent_subj <fct>, exclaim_mess <dbl>, number <fct>\n```\n\n\n:::\n:::\n\n\nc\\.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemail_pred_counts <- spam_dollar_winner_urg_aug |>\n  count(spam, .pred_class)\n\nemail_pred_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  spam  .pred_class     n\n  <fct> <fct>       <int>\n1 0     0            3551\n2 0     1               3\n3 1     0             363\n4 1     1               4\n```\n\n\n:::\n:::\n\n\nThere are 4 emails that are spam and are correctly identified. There are 363 emails that are spam that are labelled as not spam. There are 3 emails that are not spam that are labelled as spam. There are 3551 emails that are not spam and are correctly identified.\n\nd\\.\n\nThe false positive rate is 0.0844% and false negative rate is 98.9%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemail_pred_counts |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n        p\n  <fct> <fct>       <int>    <dbl>\n1 0     0            3551 0.999   \n2 0     1               3 0.000844\n3 1     0             363 0.989   \n4 1     1               4 0.0109  \n```\n\n\n:::\n:::\n\n\n21. \na\\.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemail |>\n  ggplot(aes(x = num_char, y = spam)) +\n  geom_boxplot() + \n  labs(\n    title = \"Boxplot of number of characters for spam and not spam emails\",\n    x = \"Number of characters\",\n    y = \"Spam\"\n  )\n```\n\n::: {.cell-output-display}\n![](midterm-2-practice-solns_files/figure-html/spam-vs-num-char-1.png){width=672}\n:::\n:::\n\n\nNumber of characters could be reasonable predictor of spam. Also, this plot supports differences in distributions. (I also included the predictors from Question 2 -- `winner` and `urgent_subj` in addition to `dollar`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspam_dollar_char_fit <- logistic_reg() |>\n  fit(\n    spam ~  dollar + winner + urgent_subj + num_char, \n    data = email\n  )\n\ntidy(spam_dollar_char_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term         estimate std.error statistic   p.value\n  <chr>           <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)   -1.84     0.0724     -25.5  4.23e-143\n2 dollar        -0.0206   0.0203      -1.02 3.10e-  1\n3 winneryes      2.01     0.303        6.62 3.62e- 11\n4 urgent_subj1   2.31     0.772        3.00 2.74e-  3\n5 num_char      -0.0619   0.00835     -7.41 1.26e- 13\n```\n\n\n:::\n:::\n\n\nb\\.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspam_dollar_char_fit_aug <- augment(spam_dollar_char_fit, new_data = email)\n```\n:::\n\n\nc\\.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_counts <- spam_dollar_char_fit_aug |>\n  count(spam, .pred_class)\npred_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  spam  .pred_class     n\n  <fct> <fct>       <int>\n1 0     0            3547\n2 0     1               7\n3 1     0             353\n4 1     1              14\n```\n\n\n:::\n:::\n\n\nd\\.\n\nThe false negative rate decreased to 96.2%. The false positive rate is a tiny bit higher at 0.2%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_counts |>\n  group_by(spam) |>\n  mutate(p = n / sum(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   spam [2]\n  spam  .pred_class     n       p\n  <fct> <fct>       <int>   <dbl>\n1 0     0            3547 0.998  \n2 0     1               7 0.00197\n3 1     0             353 0.962  \n4 1     1              14 0.0381 \n```\n\n\n:::\n:::\n\n\ne\\. The model from Question 21 is preferable over the model in Question 20. While the false positive rate increased, the false negative rate decreased by a larger amount; and overall more emails are categorized correctly (3547+14 = 3561 emails vs 3551 + 4 = 3555) for the model used in Question 21.\n",
    "supporting": [
      "midterm-2-practice-solns_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}