{
  "hash": "77a37bfefefcf3b520f8d25b8b64de3e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear regression with a multiple predictors I\"\nsubtitle: \"Lecture 14\"\ndate: \"2025-03-06\"\nformat: revealjs\nauto-stretch: false\n---\n\n<!-- begin: ae definition -->\n\n\n\n<!-- end: ae definition -->\n\n## While you wait...\n\n::: appex\n-   Go to your `ae` project in RStudio.\n\n-   Make sure all of your changes up to this point are committed and pushed, i.e., there's nothing left in your Git pane.\n\n-   Click Pull to get today's application exercise file: *ae\\-11\\-modeling\\-penguins\\-multi\\.qmd*.\n\n-   Wait till the you're prompted to work on the application exercise during class before editing the file.\n:::\n\n# Linear regression with a categorical predictor\n\n## From last time (with `penguins`)\n\n::: question\nA different researcher wants to look at body weight of penguins based on the island they were recorded on. How are the variables involved in this analysis different?\n:::\n\n. . .\n\n-   outcome: body weight (numerical)\n\n-   predictor: island (categorical)\n\n## Visualize body weight vs. island \n\n::: question\nDetermine whether each of the following plot types would be an appropriate choice for visualizing the relationship between body weight and island of penguins.\n:::\n\n-   Scatterplot [❌]{.fragment}\n\n-   Box plot [✅]{.fragment}\n\n-   Violin plot [✅]{.fragment}\n\n-   Density plot [✅]{.fragment}\n\n-   Bar plot [❌]{.fragment}\n\n-   Stacked bar plot [❌]{.fragment}\n\n## Visualize \n\n::: task\nVisualize the relationship between body weight and island of penguins. Also calculate the average body weight per island.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](14-linear-model-multiple-predictors-I_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Visualize \n\n::: task\nVisualize the relationship between body weight and island of penguins. Also calculate the average body weight per island.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](14-linear-model-multiple-predictors-I_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Visualize \n\n::: task\nVisualize the relationship between body weight and island of penguins. Also calculate the average body weight per island.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = island, y = body_mass_g)) + \n  geom_violin()\n```\n\n::: {.cell-output-display}\n![](14-linear-model-multiple-predictors-I_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Visualize \n\n::: task\nVisualize the relationship between body weight and island of penguins. Also calculate the average body weight per island.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(color = island, x = body_mass_g)) + \n  geom_density()\n```\n\n::: {.cell-output-display}\n![](14-linear-model-multiple-predictors-I_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n## Summarize, take 1\n\n::: task\nVisualize the relationship between body weight and island of penguins. Also calculate the average body weight per island.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(island) |>\n  summarize(\n    mean_bm = mean(body_mass_g)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  island    mean_bm\n  <fct>       <dbl>\n1 Biscoe        NA \n2 Dream       3713.\n3 Torgersen     NA \n```\n\n\n:::\n:::\n\n\n## Summarize, take 2\n\n::: task\nVisualize the relationship between body weight and island of penguins. Also calculate the average body weight per island.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  group_by(island) |>\n  summarize(\n    mean_bm = mean(body_mass_g, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  island    mean_bm\n  <fct>       <dbl>\n1 Biscoe      4716.\n2 Dream       3713.\n3 Torgersen   3706.\n```\n\n\n:::\n:::\n\n\n## Model - fit \n\n::: task\nFit a linear regression model predicting body weight from island and display the results. Why is Biscoe not on the output?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbm_island_fit <- linear_reg() |>\n  fit(body_mass_g ~ island, data = penguins)\n\ntidy(bm_island_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        4716.      48.5      97.3 8.93e-250\n2 islandDream       -1003.      74.2     -13.5 1.42e- 33\n3 islandTorgersen   -1010.     100.      -10.1 4.66e- 21\n```\n\n\n:::\n:::\n\n\n## Model - interpret \n\n$$\n\\widehat{body~mass} = 4716 - 1003 \\times islandDream - 1010 \\times islandTorgersen\n$$\n\n-   Intercept: [Penguins from Biscoe island are expected to weigh, on average, 4,716 grams.]{.fragment}\n\n-   Slope - islandDream: [Penguins from Dream island are expected to weigh, on average, 1,003 grams less than those from Biscoe island.]{.fragment}\n\n-   Slope - islandTorgersen: [Penguins from Torgersen island are expected to weigh, on average, 1,010 grams less than those from Biscoe island.]{.fragment}\n\n## Model - predict \n\n::: task\nWhat is the predicted body weight of a penguin on Biscoe island? What are the estimated body weights of penguins on Dream and Torgersen islands? Where have we seen these values before?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguins = tibble(\n  island = c(\"Biscoe\", \"Dream\", \"Torgersen\")\n)\n\npredict(bm_island_fit, new_data = new_penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 1\n  .pred\n  <dbl>\n1 4716.\n2 3713.\n3 3706.\n```\n\n\n:::\n:::\n\n\n## Model - predict \n\n::: task\nCalculate the predicted body weights of penguins on Biscoe, Dream, and Torgersen islands *by hand*.\n:::\n\n$$\n\\widehat{body~mass} = 4716 - 1003 \\times islandDream - 1010 \\times islandTorgersen\n$$\n\n. . .\n\n-   Biscoe: $\\widehat{body~mass} = 4716 - 1003 \\times 0 - 1010 \\times 0 = 4716$\n\n. . .\n\n-   Dream: $\\widehat{body~mass} = 4716 - 1003 \\times 1 - 1010 \\times 0 = 3713$\n\n. . .\n\n-   Torgersen: $\\widehat{body~mass} = 4716 - 1003 \\times 0 - 1010 \\times 1 = 3706$\n\n## Models with categorical predictors\n\n::: incremental\n-   When the categorical predictor has many levels, they're encoded to **dummy variables**.\n\n-   The first level of the categorical variable is the baseline level. In a model with one categorical predictor, the intercept is the predicted value of the outcome for the baseline level (x = 0).\n\n-   Each slope coefficient describes the difference between the predicted value of the outcome for that level of the categorical variable compared to the baseline level.\n:::\n",
    "supporting": [
      "14-linear-model-multiple-predictors-I_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}